### ISSUE TITLE
Sync never ending

### ISSUE THREAD

**Issue by GamingCoder** [Roam-Research/issues#101]
**Describe the bug**
The sync status constantly stays yellow and the following error message appeared multiple times in the console.

```
sentry.js:2 ERROR [relemma.fire.link.core:257] - 
#error {:message "Conflicting upserts: [:node/title \"\"] resolves to 5389, but [:block/uid \"03IHDYJPH\"] resolves to 5400", :data {:error :transact/upsert, :entity {:create/time 1588614815453, :node/title "", :block/uid "03IHDYJPH", :block/refs [], :create/email "tobiasvalentinmeyer@gmail.com", :edit/time 1588614815455, :edit/email "tobiasvalentinmeyer@gmail.com", :block/_refs 5403}, :assertion [5400 :block/uid "03IHDYJPH"], :conflict [5389 :node/title ""]}}
```

**To Reproduce**

1. Open Developer Tools
2. Rightclick on Reload button and select "Empty cache and hard reload"
3. Look in console

**System Information:**
 - Macbook
 - OS: Mac OS Catalina 10.15.4
 - Chrome 81.0.4044.129

**Additional context**

I wanted to try the fix for issue #49 mentioned in the comments.

**Comment by panterarocks49** [comment]
Hey we pushed up some changes the other day that should fix this, is this still an issue for you?

**Comment by filipesilva** [comment]
Closing as we think this was sorted, and the author didn't get back to us.

**Comment by GamingCoder** [comment]
Sorry for not getting back to you. I have pretty much completely switched to GitLab and don't log in here anymore. I have not seen this kind of issue since.
