### ISSUE TITLE
Daily Notes Page Lost

### ISSUE THREAD

**Issue by s-kyy** [Roam-Research/issues#102]
I was trying out Roam today (started a couple of days ago). I kept the tab pinned to my browser (FireFox) overnight and used it this morning again. I was messing with page titles by correcting the title names that had typos and merging them when prompted. Due to these pages not keeping the proper titles when I corrected them I force refreshed the roam page multiple times. Eventually the Daily Notes page for May 5, 2020 just dissapeared. The pages created under that daily note like [[Projects]], [[Areas]], [[Archive]], etc still exist but are not connected to May 5, 2020 anymore. I tried refreshing the page a few more times, but it stays missing and even though today is May 5, the daily notes don't make the new empty page with that date. This didn't happen on the prior days I was using it (May2-4). 

**To Reproduce**

Not sure what exactly triggers it. Sorry :(

**System Information:**
 - Device: ASUS Zenbook 14
 - OS: Windows 10
 - Browser: Firefox

**Additional context**

I've seen other issue bring up problems of missing blocks. I don't think that occurred in this case.  

EDIT: 
Additionally, the orange dot is always there, so I guess it's constantly saving even though I haven't been typing anything for >30 minutes. 

When I search for the note May 5th, 2020, the site stays stagnant. Clicking on other dates immediately jumps to those pages

**Comment by JaviFuentes94** [comment]
Same bug here regarding May 5th. I cannot access this day in the daily notes, and all of the stuff that was there was lost.  


- Device: Dell Inspiron
- OS: Ubuntu
- Browser: Chrome

**Comment by carlodicelico** [comment]
Just trying out Roam and I'm also having this issue. None of my pages stick around, links are lost (like Roam forgets when a page is created), etc. Seems related to data synchronization because the data sync indicator stays orange. Also possibly related, the graph doesn't show my newly created pages.

**Comment by swoopapp** [comment]
same issue!

**Comment by filipesilva** [comment]
Heya, we've recently fixed some synchronization bugs. Can you try force refreshing your web page to get the latest version? If you're still seeing this let me know.

**Comment by s-kyy** [comment]
Things seem to be working properly. The syncs are done in a reasonable amount of time. My May 5th notes are still lost. Thanks though.
