### ISSUE TITLE
Html to Markdown converter (on paste) inserts a lot of extra newlines

### ISSUE THREAD

**Issue by Stvad** [Roam-Research/issues#104]
**Describe the bug**

When you copy-paste text from the web pages - the Html to Markdown converter often ends up inserting a lot of extra newlines into the text requiring you to do a lot of post-processing to get a properly formatted text inside roam.

Example by copying text from https://networkedthought.substack.com/p/learning-effectively-with-podcasts

![image](https://user-images.githubusercontent.com/81347/81132438-45fb6a80-8f03-11ea-90cb-d151b11b94fd.png)

**To Reproduce**

1. Go to https://networkedthought.substack.com/p/learning-effectively-with-podcasts
2. Copy a few paragraphs of text
3. Paste them into the Roam
4. Behold all the newlines

**System Information:**
 - Device: desktop
 - OS: Mac
 - Browser: Chrome

**Comment by GitMurf** [comment]
@Stvad I think my issue I created #105 is similar? This makes it very hard for any of my scripting and currently attempt at the Chrome "highlighter" I built because I can't get text to be put in a format to be interpreted by Roam the way it should when pasting.

**Comment by Stvad** [comment]
No, I believe the #105 is a separate thing. In case of this issue - I'm talking about unexpected newlines within the block. #105 is about splitting a paragraph into several blocks

**Comment by GitMurf** [comment]
Sorry, I didn’t mean they were same issue but what I meant was related to similar problem where HTML / Clipboard to Markdown “converter” or “interpreter” or whatever you want to call it is having issues and not doing what we expect. And both have to do likely with how and what Roam reads / considers “new line” characters.

**Comment by Bardia95** [comment]
@Stvad is this still an issue for you? I tried to reproduce but the paragraphs from the site you sent are working fine on my Roam

**Comment by Stvad** [comment]
it seems to have been fixed now :)!
