### ISSUE TITLE
Sync does not finish at all - orange dot

### ISSUE THREAD

**Issue by ebrellne** [Roam-Research/issues#106]
Since the day before yesterday my changes are not saved on your server. I am really scared that I lose all my progress. I used Roam hours for my project. 

<img width="554" alt="Bildschirmfoto 2020-05-06 um 07 19 43" src="https://user-images.githubusercontent.com/64885443/81140613-51ce4780-8f6a-11ea-892f-8679d3a9e8c0.png">

**To Reproduce**
<img width="347" alt="Bildschirmfoto 2020-05-06 um 07 21 20" src="https://user-images.githubusercontent.com/64885443/81140668-7e825f00-8f6a-11ea-93f2-687eef9ca48b.png">

**System Information:**
 - Device: Macbook Pro
 - OS: macOS Catalina Version 10.15.3
 - Browser Chrome 81.0.4044.129

**Comment by ebrellne** [comment]
I made a hard reload of chrome. now this is showing in the orange dot with no process for hours.

<img width="301" alt="Bildschirmfoto 2020-05-07 um 15 31 07" src="https://user-images.githubusercontent.com/64885443/81300560-1d48b180-9078-11ea-9069-10b161c916f2.png">

Please help!

**Comment by neilkakkar** [comment]
Related to #120

**Comment by filipesilva** [comment]
Heya, I added an update about this in https://github.com/Roam-Research/issues/issues/120#issuecomment-625467819.
