### ISSUE TITLE
Stuck on Loading Page, Error Message in Console

### ISSUE THREAD

**Issue by dfeng** [Roam-Research/issues#108]
**Describe the bug**

Stuck on Loading Page (and then computer fan starts revving). Get error message in Console:

` ERROR [relemma.fire.link.core:218] - [DEFAULT] - error while applying confirmed tx #error {:message "Nothing found for entity id [:block/uid \"05-05-2020\"]", :data {:error :entity-id/missing, :entity-id [:block/uid "05-05-2020"]}}`

My guess: something weird happened during syncing.

**System Information:**
 - Device: Desktop
 - OS: Mac
 - Browser: Safari/Firefox

**Comment by dfeng** [comment]
Any updates? I suspect this is specific to my account (username: supremum), as many people (on reddit) seem to be back to normal. Apologies for bumping, but I would love to be able to access my notes (was writing my papers in roam).

**Comment by filipesilva** [comment]
@dfeng can you try force refreshing now? Please tell me if this is still happening afterwards.

**Comment by dfeng** [comment]
Thanks for getting back to me. I emptied the cache and retried, but now it just hangs during the websocket ping (and most times, my browser window stalls and crashes). There is no more error message. I've tried it on a complete new browser (Chrome), and the same thing happens.

At this point, I'd just be happy if I could get the data exported. I don't want to waste your time searching for a bug that's probably specific to my account.

**Comment by filipesilva** [comment]
@dfeng unsure what's happening, do you want to ping me on the slack and I'll sort it out with you?

**Comment by dfeng** [comment]
It looks like the slack channel link doesn't work?

**Comment by filipesilva** [comment]
Just updated it, it was supposed to not expire but somehow did :|

**Comment by filipesilva** [comment]
Chatted over slack, seems like there was something on the daily log that caused it to crash. Solved by opening https://roamresearch.com/#/app/DATABASE_NAME_HERE/search then trying to open individual daily log pages to find what's wrong. Waiting on @dfeng to let me know if he finds the exact problem.

**Comment by dfeng** [comment]
It was the latest daily page (May 5th, 2020). Interestingly, when I export it with markdown, nothing appears for that entry. For JSON, we get this:

```{json}
{
   "title":"May 5th, 2020",
   "children":[
      {
         "string":"",
         "create-email":"REDACTED",
         "create-time":1588673243708,
         "children":[
            {
               "uid":"yMi2B51Ez"
            },
            {
               "children":[
                  {

                  }
               ],
               "uid":"05-05-2020",
               "edit-time":1588673241714,
               "edit-email":"REDACTED"
            }
         ],
         "uid":"Ip87Lxx1a",
         "edit-time":1588673243708,
         "edit-email":"REDACTED"
      }
   ],
   "edit-time":1588673241714,
   "edit-email":"REDACTED"
}
```

Hmmm. Not sure what's going on here.

**Comment by filipesilva** [comment]
I think I've seen one similar case where empty children would cause odd behaviour. The empty child would be caused by data loss. @panterarocks49 can we ignore those?

**Comment by dfeng** [comment]
also, the uid is a date? is that a bug?

**Comment by filipesilva** [comment]
No that's normal actually, daily pages have the date as uid. Helps prevent duplicate insertion by different clients.

**Comment by dfeng** [comment]
In any case, thanks! It feels very bittersweet to be back (I actually ended up setting up my own local "version" of roam, utilizing `sublime_zk`, during the downtime).
