### ISSUE TITLE
Remote Changes pending

### ISSUE THREAD

**Issue by anshbansal** [Roam-Research/issues#118]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4127841/81257702-984aa180-9051-11ea-8560-3b66623b83b2.png)

This number is not going below 65. Also, there are some bullets that have become read-only. It is quite possible they have been edited but they get sent to the server but the actual changes are not coming down so that's why they seem like read-only. New changes are going to the server and even if I am reloading I am not seeing any problem with data loss except few bullets going read-only. 

**To Reproduce**

No idea

**System Information:**
 - Roam version: 0.5.0-eecdac3b
 - Device: desktop computer
 - OS: MacOS Catalina 10.15.4 (19E287)
 - Browser Brave

**Comment by anshbansal** [comment]
Was able to solve this by clearing application cache in browser. Missed some data after clearing cache. But because I had the exports in git before clearing cache I was able to find the diff and put that back in.

**Comment by jammastergirish** [comment]
I also have this issue. If I clear the cache, will I lose some blocks? It sounds like it. If so, where can I find them to copy manually? Thank you!

![Screenshot 2020-05-07 at 21 18 53](https://user-images.githubusercontent.com/16509800/81315821-6add1280-90a8-11ea-8a44-202b7cb2e932.png)

**Comment by archy8088** [comment]
same questions.
![image](https://user-images.githubusercontent.com/61367474/81317646-af27dd00-90bf-11ea-9901-5e0dcdef6894.png)

**Comment by jammastergirish** [comment]
From the Slack group:

Girish Gupta(opens in new tab) Today at 9:29 PM
I know a lot of us here are facing hours of the orange dot and scared to navigate away/clear cache, etc. For peace of mind, if we were to export all to JSON/MD, would this include our non-synced data or does it just download what's on the server anyway? (This is a question about how the export function works.) Thanks!
2 replies

Matias Faure(opens in new tab)  12 minutes ago
It will export the local data

Girish Gupta(opens in new tab)  10 minutes ago
Oh great! So, worst case scenario, I do have my data. Thanks for the quick response.
:+1:
1

**Comment by filipesilva** [comment]
Heya, I added an update about this in https://github.com/Roam-Research/issues/issues/120#issuecomment-625467819.
