### ISSUE TITLE
Markdown Links are treated as Unlinked References

### ISSUE THREAD

**Issue by ryanguill** [Roam-Research/issues#12]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1149698/79878204-c8881400-83b2-11ea-8ac5-cf46fa40fb86.png)

Markdown links such as `[test]([[page]])` are shown as unlinked references instead of linked references.

Separately, clicking the "link" link beside the reference does nothing.

I am fairly confident this was working properly at one point, not that long ago.

**To Reproduce**

1. make a markdown link such as (type this) `[Yesterday](/yesterday)`.  
2. click it to go to the daily page for yesterday, see that it is in unlinked references
3. click the "link" link next to it and see it does nothing.

**Comment by JasperGeh** [comment]
In my experience, this creates a page with the second letter of the [[Page]] as a title.
Clicking the link takes me to the [[Page]] and not the single letter, but it explains where the linked reference went!
![image](https://user-images.githubusercontent.com/28384742/79880977-f8560c80-83f0-11ea-835b-bacc6898a016.jpeg)

**Comment by classicrob** [comment]
I closed my issue because I realized it was replicated here.  "Markdown links such as [test]([[page]]) are shown as unlinked references instead of linked references" is very frustrating for me and reduces general readability and findability of information.

**Comment by classicrob** [comment]
@panterarocks49 why is this closed?  Seems to still be an issue.

**Comment by JasperGeh** [comment]
As far as I can tell, it was fixed. References in Md links created earlier were still not linked for me, but new Md links are being linked correctly.

**Comment by classicrob** [comment]
Hmm I was looking at my past markdown links and those aren't working... that's frustrating. Are there any plans to fix this?

For now, I made a page ([[.  I'm going through the unlinked references one by one, clicking into the markdown link, deleting a bracket, clicking out of the block, clicking back into it, adding the bracket back in.

**Comment by classicrob** [comment]
I'm glad that it was fixed going forward though
