### ISSUE TITLE
All new edits instantly rolled back + data loss (making Roam unusable)

### ISSUE THREAD

**Issue by ibaghdadi** [Roam-Research/issues#120]
**Describe the bug**
All new edits I'm making to my Roam notes are being rolled back within seconds. My notes are effectively in read-only mode.

Had the orange dot for several days, didn't assume it was a problem since everything worked well and I backed up daily.

This morning I had to restart the computer. When the computer restarted, all of my notes looked perfect, just as I left them. Roam still had the orange dot.

Within a few minutes however, my notes reverted to how they were several hours earlier (resulting in data loss of all edits since).

Since then, I am unable to make any changes to any notes. Any changes I make are reverted within seconds. This is happening without fail (not randomly).

It's still on orange dot, with the status sometimes online and sometimes offline. 1715 changes pending, otherwise I would have hard-refreshed...

**To Reproduce**
Not sure, but this is how it happened for me:
1. Start with a Roam account that is stuck on orange
2. Refresh page (or in my case, restart computer)
3. Check if there's any data loss (in my case there initially wasn't)
4. Wait for a few minutes and check again... see data loss
5. Try to make new changes or edits... see bug

**System Information:**
 - Roam version: [0.5.0-eecdac3b]
 - Device: [e.g. Google Pixelbook]
 - OS: [Chrome OS version 81.0.4044.127 (64 bit)]
 - Browser [Chrome]

**Additional context**

I don't use Roam from any other browser or tab, and haven't used it from mobile in over a week

**Comment by tvanantwerp** [comment]
Experiencing the same issue. I can create new blocks, but all edits to old ones are instantly reverted. Remote changes haven't been made in two days.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/2487968/81297419-384bff00-9041-11ea-850d-e5026437c78d.png">

**Comment by neilkakkar** [comment]
Same issue, Roam is stuck on  a remote change and sentry logs in the console go like:

```
sentry.js:2 ERROR [relemma.fire.link.core:268] - 
#error {:message "Cannot add #datascript/Datom [27257 :block/uid \"-WPhWy9KM\" 536908701 true] because of unique constraint: (#datascript/Datom [27409 :block/uid \"-WPhWy9KM\" 536908698 true])", :data {:error :transact/unique, :attribute :block/uid, :datom #datascript/Datom [27257 :block/uid "-WPhWy9KM" 536908701 true]}}
```

**Comment by neilkakkar** [comment]
@panterarocks49 - do you have a resolution note?

**Comment by filipesilva** [comment]
Hey all, first of all I'm sorry that this problem happened. We had a little bit of code that wasn't backwards compatible that we deployed yesterday or so and caused this issue. We've now deployed a fix for this problem. You should start seeing it the "stuck" transactions drain after you update by doing a hard refresh (ctrl+f5 on windows, ctrl+shift+r).

A big thanks to @ibaghdadi for spending a fair amount of time debugging and getting information for me from his roam db to debug this!

**Comment by neilkakkar** [comment]
Can confirm all good, thanks.

**Comment by jammastergirish** [comment]
Thank you. On doing the hard refresh, will we lose data or will that be saved locally and then uploaded?

> Hey all, first of all I'm sorry that this problem happened. We had a little bit of code that wasn't backwards compatible that we deployed yesterday or so and caused this issue. We've now deployed a fix for this problem. You should start seeing it the "stuck" transactions drain after you update by doing a hard refresh (ctrl+f5 on windows, ctrl+shift+r).
> 
> A big thanks to @ibaghdadi for spending a fair amount of time debugging and getting information for me from his roam db to debug this!

**Comment by filipesilva** [comment]
@jammastergirish should be saved locally, but there might be ordering problems. I expect ordering problems to always result in the "instant roll back" though, so whatever you see now is what should be there after the reload.
