### ISSUE TITLE
Quick Capture's "yesterday" option created a blank page with no name

### ISSUE THREAD

**Issue by tmm1** [Roam-Research/issues#127]
**Describe the bug**

I signed up for Roam, then a few days later I started using it. I was on my phone using Quick Capture, and selected "yesterday". When I synced these notes to my full workspace, a page with no name or link was created with the contents.

It looks like Roam does not let you create pages for days in the past, so somehow that's interacting weirdly with the Quick Capture.

**To Reproduce**

1. sign up for roam
2. wait two days
3. use quick capture to add a note for yesterday
4. sync to workspace

**Comment by panterarocks49** [comment]
Deploying a fix for this today
