### ISSUE TITLE
Code block creation is fiddly

### ISSUE THREAD

**Issue by neildurant** [Roam-Research/issues#13]
**Description**

When inserting a multi-line code block, the natural inclination is to press three back-ticks, type the first line, then hit enter, and continue adding lines, and finally add three closing back-ticks, similarly to how you'd do it in Slack. However this breaks as soon as you hit enter.  Roam interprets the first two backticks as an opening/closing single-line code block, then renders the third backtick as just a literal backtick.

Expected behaviour would be that when you type three back-ticks, it auto-completes the closing three back-ticks (same as if you enter opening delimiters of various types). Then you should be able to type in code, pressing enter, and see the code block grow accordingly.

The awkward workaround seems to be to enter the first line of the code block, including its closing backticks, hit enter, and then click into the code block and start adding lines, all of which is rather awkward.

**To Reproduce**

(Using ' instead of backtick, for the purposes of sanity in entering markdown)

1. Type:  '''Line 1  (press enter)
2. Observe it shows: `   `'Line 1   (empty singe-line code block at the start)
3. Observe that the cursor is on a new block, not in the code block

**System Information:**
 - Device: Desktop computer
 - OS: Windows 10
 - Browser: Brave

**Comment by mmower** [comment]
I've been completely unable to make multi-line code blocks work. Thanks for the workaround @neildurant

**Comment by cori** [comment]
On the Mac, at least, using Shift+Enter instead of hard returns within the code block allows Roam to interpret the content as a block. I’ve also had luck with using Shift+Cmd+V to paste content “without formatting” is this case as well. 

I agree that having a “proper” code-block editor (as you say, Slack does this well, I think) would be lovely.

**Comment by neildurant** [comment]
Aha, thanks @cori, Shift+Enter works on Windows too.

**Comment by maxcodes** [comment]
I just type six backticks in a row, hit enter, and then I can type/paste the snippet inside of the rendered box. 

Much simpler than the approaches mentioned so far

**Comment by cori** [comment]
> I just type six backticks in a row, hit enter, and then I can type/paste the snippet inside of the rendered box.

Nice! TIL!
