### ISSUE TITLE
Public read-only database is being edited by other people

### ISSUE THREAD

**Issue by Nateliason** [Roam-Research/issues#132]
My public database: https://roamresearch.com/#/app/RoamTutorial/ is read-only, but people are making edits to it. You can see some examples: 

- https://roamresearch.com/#/app/RoamTutorial/page/lYfvZq-2S
- https://roamresearch.com/#/app/RoamTutorial/page/05-03-2020

It's happened on a number of other pages too, not sure where this is coming from.

**Comment by Stvad** [comment]
Just went there and was able to do drag&drop

**Comment by Stvad** [comment]
But I suppose that given that the server accepts any changes from me at all (which it shouldn't), I can probably do arbitrary changes..

**Comment by panterarocks49** [comment]
we deployed a fix for this today, reopen issue if it comes up again

**Comment by annieeby** [comment]
I notice I can change the code block language ; I am not an editor. 
![image](https://user-images.githubusercontent.com/13418713/108558860-c84cf380-72b7-11eb-9c58-737e3dd7aedf.png)

**Comment by annieeby** [comment]
I notice I can change the code block language ; I am not an editor.
![image](https://user-images.githubusercontent.com/13418713/108559013-f9c5bf00-72b7-11eb-9e80-e1621d87080c.png)
