### ISSUE TITLE
Improvement to search feature.

### ISSUE THREAD

**Issue by abhyantrika** [Roam-Research/issues#137]
**An improvement to the search feature.**
I have the habit of keeping my pages clean and hence "close all the drop-downs" to the important section headers. Now, when I am in some other page and search for a line or a term, it takes me to the relevant page. But it does not expand the drop downs and take me to the exact line where the term was found. 
Atleast for my use case, this becomes annoying as I have to click through and search from each of the drop downs myself. 

**Feature implementation**
A simple extension to search UI that takes you to the exact line you were searching and maybe highlights the line.

**Comment by panterarocks49** [comment]
Deploying a change so selecting the found block will take you to the zoomed in block, will be up in a few minutes
