### ISSUE TITLE
Alt/Option click-and-drag to create a block reference does not work in Firefox

### ISSUE THREAD

**Issue by pmbauer** [Roam-Research/issues#14]
**Describe the bug**

Alt/Option click-and-drag to create a block reference is broken in Firefox

**To Reproduce**

[Link to Screen Capture](https://www.dropbox.com/s/amif7ngyyw14mox/Apr-21-2020%2012-06-47.mp4?dl=0)

1. Go to any page with a page reference
2. Shift-click the link to bring up the reference in the side bar
3. Hold down Alt/Option and click a block in the side bar.
4. Attempt to drag the block to the active page to create a reference.
5. No reference is created

**System Information:**
 - Device: desktop computer
 - OS: MacOS 10.15.4
 - Browser: Firefox 76.0b6

**Comment by ryanguill** [comment]
I see the same thing, doesnt work in Firefox on Mac. Does work in Chrome.

**Comment by pmbauer** [comment]
Happily, it also works in Safari on Mac

**Comment by panterarocks49** [comment]
Took a look at this today, it looks like there's bug (different behavior?) in firefox where the drag event doesn't fire with alt/option key held down. Going to add the option to copy block refs the cmd-drag so it's still possible

**Comment by pmbauer** [comment]
@panterarocks49 🙇
