### ISSUE TITLE
Safari Highlight Shortcut Doesn't Work (cmd + h)

### ISSUE THREAD

**Issue by mscheibe** [Roam-Research/issues#140]
**Describe the bug**

`cmd + h` -> On macOS will hide current app and Safari doesn't let you steal this shortcut. Seemed to be fine in Brave browser.

**To Reproduce**

1. Use Safari on latest macOS
2. Select some text and hit `cmd-h`
3. It doesn't highlight (but it also doesn't 

**System Information:**
 - Roam version: 0.6.1-aacf1e8e
 - Device: desktop
 - OS: macOS
 - Browser Safari

**Additional context**

**Comment by panterarocks49** [comment]
Similar problem to https://github.com/Roam-Research/issues/issues/143, `cmd-h` event never fires on safari, will add `cmd-shift-h` option to highlight today
