### ISSUE TITLE
Safari "Show Previous Page" shortcut broken

### ISSUE THREAD

**Issue by mscheibe** [Roam-Research/issues#141]
**Describe the bug**

`cmd + [` is used to navigate back in browser history, but in Roam it starts opening page reference `[]`, breaking the browser shortcut.

**To Reproduce**

1. Click a link in roam
2. Type `cmd + [` to go back
3. See `[]` instead

**System Information:**
 - Roam version: 0.6.1-aacf1e8e
 - Device: desktop
 - OS: macOS
 - Browser Safari

**Additional context**

**Comment by pratul** [comment]
Can confirm this is also happening on Firefox on macOS Catalina 10.15.4.

**Comment by weiliddat** [comment]
This also happens in macOS 10.15.4, Chrome 81

**Comment by pmbauer** [comment]
I think this is working as expected.
If you type `cmd + [` while editing a block, it types `[`, but if you hit escape first (leave block edit mode) navigation works fine.

**Comment by panterarocks49** [comment]
Will push up a fix for this today, no need for `cmd-[` to enter `[]`
