### ISSUE TITLE
Zoom out shortcut broken in Safari on macOS

### ISSUE THREAD

**Issue by mscheibe** [Roam-Research/issues#142]
**Describe the bug**

`cmd + ,` -> Opens current app preferences, i.e. Safari Preferences, so cannot zoom out
**To Reproduce**

1. Type `cmd + ,`
2. See Safari Preferences

**System Information:**
 - Roam version: 0.6.1-aacf1e8e
 - Device: Desktop
 - OS: macOS
 - Browser Safari

**Additional context**

**Comment by pratul** [comment]
This is a (near) duplicate of #143.

**Comment by Stvad** [comment]
yeah, it's not a Safari thing, it's macOS thing as described in #143

**Comment by mscheibe** [comment]
Zoom out works in Chrome on macOS.

**Comment by panterarocks49** [comment]
Closing in favor of https://github.com/Roam-Research/issues/issues/143
