### ISSUE TITLE
Deleting a page

### ISSUE THREAD

**Issue by agentydragon** [Roam-Research/issues#148]
**Describe the problem**

I often create pages on mistake - for example, by making typos in links. As far as I know there's no way to remove pages. If you remove the title of a page, it will stop showing up as a suggestion in autocomplete, but it will still show up on the graph as a lonely node.

**Feature implementation**

Have a menu option on pages to delete them. Or, to make this reversible, instead of deleting, it could be worded as "archiving", with pages being possible to unarchive.

**Comment by everruler12** [comment]
There's already an option in the 3-dot menu to permanently delete a page.

![Screenshot](https://user-images.githubusercontent.com/64292121/81476729-72540700-91e1-11ea-91ac-e5f9be2be64c.png)

**Comment by agentydragon** [comment]
Oops. Thanks!
