### ISSUE TITLE
Selecting text and Ctrl+B twice should bold and then unbold text

### ISSUE THREAD

**Issue by agentydragon** [Roam-Research/issues#149]
**Describe the problem**

Select `some text` in Roam and press Ctrl+B. That makes it become `**some text**`. Without changing selection, press Ctrl+B again. The result is: `****some text****`.

I'd expect that, like in most editors (e.g. Google Docs) Ctrl+B is "toggle bold", not just "one-way make bold".

I'd expect that if the selected text is just part of an already bolded section, it would get unbolded.

I'd expect that if the selected text has mixed boldness, it would be all bolded.

Same thing applies for the other formatting options (italic, highlight)

**Comment by panterarocks49** [comment]
Deploying a fix for this today
