### ISSUE TITLE
Make Roam web app a share target on Android

### ISSUE THREAD

**Issue by agentydragon** [Roam-Research/issues#162]
**Describe the problem**

Very often I want to take something I find on the internet and put it into my notes. My workflow with Google Keep has been via the system Share function - e.g, I find some interesting webpage, click the Share button in Chrome, select Keep, save the note.

This is also super useful in that you can select a text in any app, click Share, and send it into Keep.

Roam web app does not seem to allow this. You need to use the system clipboard, which is much more slow and annoying - especially if at the point of "now I open Roam and add it to Quick Capture" you encounter the Astrolabe of Death.

**Feature implementation**

For example, this is how you can select text and easily send it to Keep: ![](https://images.idgesg.net/images/article/2019/01/20-google-keep-android-share-100785981-large.jpg)

Note that it lets you also easily add tags and edit the text before saving.

**Additional context**

I'd love to switch to using Roam for all my note-taking. But on mobile, not supporting the Android Share protocol is really making it much slower to add things than if I use Keep. If Roam had this, I would actually probably switch to it for *all* my note-taking needs. But unfortunately, using it on Android instead of Keep introduces way too much friction.

**Comment by agentydragon** [comment]
Also, this seems to talk about how to implement this: https://chodounsky.com/2019/03/24/progressive-web-application-as-a-share-option-in-android/

**Comment by agentydragon** [comment]
Looks like Roam PWA now supports this, yay :)

**Comment by panterarocks49** [comment]
we have this now!
