### ISSUE TITLE
Show block details, and not block id in kanban boards

### ISSUE THREAD

**Issue by tejovanthn** [Roam-Research/issues#171]
**Describe the bug**

The kanban board does not expand the block reference as expected, and shows only the block id.

![image](https://user-images.githubusercontent.com/1077633/81525269-bfff7980-9371-11ea-8295-46c2ad515871.png)

**To Reproduce**

1. Create a kanban board.
2. Add a block reference as a card.
3. The block reference expands in the list view, but does not expand inside the card.
4. See bug

**System Information:**
 - Roam version: 0.6.1-fb84ed08
 - Device: Desktop
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Comment by filipesilva** [comment]
@panterarocks49 @wilkerlucio is this intended? It makes the kanban pretty hard to read.

**Comment by tejovanthn** [comment]
Spotted this in version: `0.6.2-54e64415`
