### ISSUE TITLE
Block embed not pulling in sub-bullets on some pages

### ISSUE THREAD

**Issue by maefleurs** [Roam-Research/issues#174]
The block embed feature is only pulling in the first line, not the sub-bullets.

1. I wrote notes for a meeting on my Daily Notes page.
2. I tagged the first line of this meeting with the [[Project Name]]
3. On the page for [[Project Name]], I created a block embed for the notes from that particular meeting so that it will show in the main page (in addition to the linked references)
4. There *are* many sub-bullets under the first line for the meeting, but only the first line gets pulled into the block embed

Notes: 
- The block embed feature is working as expected when I try to pull a block from another page onto my Daily Notes page

If you need screenshots or a video, DM me in Slack (@Anna Fuller)

**System Information:**
 - Roam version: 0.6.1-fb84ed08
 - Device: desktop
 - OS: MacOS 10.15.4 (19E287)
 - Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

n/a

**Comment by maefleurs** [comment]
Update: I think the issue here is that the first line of the embed cannot be expanded/closed in the place where it is embedded; only in the original place it lives. My expectation is that any part of the embedded block can be expanded/closed or edited from any place where the block lives, whether it is written directly or embedded.

**Comment by filipesilva** [comment]
@panterarocks49 is this something we want to support?

**Comment by maefleurs** [comment]
Noticed that there's an update here! Now, when I hover over the block embed, if the first line can be expanded I see the expander arrow appear. Very nice! Resolving this issue.
