### ISSUE TITLE
Ignore Keypress for Command+Control+[

### ISSUE THREAD

**Issue by iwsmith** [Roam-Research/issues#180]
**Describe the bug**

When I use keyboard shortcuts to switch tabs in my browser (Command+Control+[) an open bracket `[` is inserted into the text I was typing in. Other Command+Control combos (copy, paste) don't exhibit this behavior.

**To Reproduce**

1. Go to any editable block
2. Select the text so you can start typing
3. Use the keyboard shortcut to switch tabs (Command+Control+[)
4. See a `[]` in your text now (whenever you come back to the tab).

**System Information:**
 - Roam version: 0.6.1-98eeb3de
 - Device: Mac Laptop
 - OS: OSX 10.15.4
 - Browser: Firefox Nightly

**Comment by panterarocks49** [comment]
Will push up a fix for this today
