### ISSUE TITLE
Changes are not synced

### ISSUE THREAD

**Issue by eBerdnA** [Roam-Research/issues#198]
**Describe the bug**

Changes made on one device don't get synced to the database even though the traffic light states everything is synced. 
So basically daily notes for 11th May are in my database on device "a" and the traffic light is green and states that everything has been synced.
On device "b" the traffic light is green and states that everything is synced but daily notes for 11th May do not exist on device "b".

The above described example also applies to other pages.

**System Information:**
 - Roam version: 0.6.1-cee6d00b
 - Device: desktop computer 
 - OS: Windows 10
 - Browser Microsoft Edge Version 81.0.416.72 (Official build) (64-bit)

If I can/should/need to provide any further information just let me know.

**Comment by eBerdnA** [comment]
Update:
Something must have changed between 9 and 10 PM CEST UTC+2. Because now all changes have been synced and show up at the other device.

Did you make any changes to RoamResearch or the backend database during this timeframe?

**Comment by filipesilva** [comment]
@eBerdnA we made a couple od deployments yesterday, 2 of which I imagine could be interacting with the problem you were seeing. Let me know if you have problems with it again!
