### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by jaste111** [Roam-Research/issues#199]
If I try to login with chrome I am stuck on the loading screen. 

This is due to a cookie 
"A cookie associated with a resource at http://roamresearch.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032"

If I delete this cookie and reload the page I workes and I can log in.

**System Information:**
 - Roam version: 0.6.1-cee6d00b
 - Device: Desktop computer
 - OS: Ubuntu
 - Browser Chrome

**Comment by filipesilva** [comment]
@jaste111 can you try force reloading now please? Should be ctrl+f5 on linux chrome.

**Comment by jaste111** [comment]
@filipesilva No, sorry. I deleted the cookie so I can log in again. The bug did not occur after this again.

**Comment by filipesilva** [comment]
Ok, thanks for the update.

**Comment by chinarut** [comment]
I’ve run into this bug on iPadOS Safari 14.4 (iPad Pro (2018))

Deleting the cookie for roamresearch.com allows the page to load and the bug comes back daily.

My workaround was previously to use iOS Chrome and now it gets stuck too.

I would prefer to use Desktop Safari over Chrome.
