### ISSUE TITLE
Clicking a {{[[TODO]]}} checkbox inside a block reference will simultaneously tick it and take you to that bullet

### ISSUE THREAD

**Issue by Lunariz** [Roam-Research/issues#2]
**Describe the bug**

When ((Block referencing)) a block that contains the todo tickbox {{[[TODO]]}}, you can correctly click the tickbox to tick it. However, when ticking it, you are also 'clicking' the block reference, meaning that you are taken to the block that is being referenced.

The expected intention is just ticking the box, and being transported to another page is an annoying side-effect.

**To Reproduce**

1. Create a bullet containing {{[[TODO]]}}
2. Create a ((block reference)) to the TODO bullet
3. Click the checkbox inside the block reference

**System Information:**
 - Device: Desktop computer
 - OS: Windows
 - Browser: Chrome

**Additional context**

I feel like in general, 'click block reference to go there' is quite error-prone. Additionally, the fact that it takes you all the way down to that specific bullet (rather than showing the containing page & relevant context) makes that I almost never use it, or I use it and then immediately navigate to the containing page (2 clicks)

**Comment by cori** [comment]
I can reproduce this in Safari on a Mac as well.

**Comment by MarcCoet** [comment]
Same thing for links.
External links will open in a new tab while Roam navigated to the ref in the initial tab.
Internal links will make Roam navigate twice, first to the link and then to the referenced block.

IMO click events should not propagate to the reference link when clicking on a target inside the reference. We can always click "around" the checkbox or the text link if we want to trigger the reference link.
(I hope it is clear. I am lacking proper naming conventions here)

**Comment by panterarocks49** [comment]
Deploying a fix for this today, should be up in about 20 minutes

**Comment by mg0716** [comment]
So happy with this change! Thanks @panterarocks49 !
