### ISSUE TITLE
Nicknames for pages

### ISSUE THREAD

**Issue by maugermika** [Roam-Research/issues#204]
**Describe the problem**

The issue is quite simple : 
The title of one Roam page is unique.
e.g. the page [[New York]]
Therefore if I ever want to say "I went to [[NY]]" for instance, it would create a new page.
The solution would be to merge these pages and get only one 'New York' page.
The same goes if I forgot the capital letters [[new york]], or if I speak another language [[Nueva York]].

(https://roamresearch.com/#/app/help/page/kthU0dTqW)
This page is about disambiguation of a same title, what about several titles for a same page ?

**Feature implementation**

I am French and when I write in English, I want to be able to link to the same page when I write [[Philosophy]] as when I write [[Philosophie]] (or [[Fillosofía]] if I ever write in Spanish) and not write French words in English texts and vice versa.

So what I propose is a 'Nickname' or 'aka' bar/bullet/button just below page titles where you can insert title names that relate to the same word/idea/title name in the occurence of :
- same word, capital letter difference
- acronym instead of full name
- word translation in another language

**Additional context**

I think this would really help bilinguals and polyglots, or even people learning a new language. 
It would simplify linking ideas without the barrier of language.

p.s. I love Roam

**Comment by Stvad** [comment]
dup of #175 I believe

**Comment by maugermika** [comment]
Indeed, I have exactly the same page as #175 ; thank you for noticing
