### ISSUE TITLE
Error on Import Files

### ISSUE THREAD

**Issue by sdaviss** [Roam-Research/issues#206]
Importing .md files does not work due to an ERROR message.

See below screenshots and descriptions. Import files > Select file > Error message.
**To Reproduce**

---
# 1. Click on ellipsis at top right of screen.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/5508226/81886013-a45ec380-9569-11ea-85da-0c18bb493a87.png">

## .. 

---
# 2. Click on 'Import Files'
<img width="336" alt="image" src="https://user-images.githubusercontent.com/5508226/81886110-dd973380-9569-11ea-868f-e835cec00533.png">

## ..

---
# 3. Click on 'Choose Files' on prompt to select Markdown or JSON file.
<img width="335" alt="image" src="https://user-images.githubusercontent.com/5508226/81886203-16cfa380-956a-11ea-9d46-05934b09a065.png">

## ..

---
# 4. Select a .md file.
<img width="85" alt="image" src="https://user-images.githubusercontent.com/5508226/81886254-35ce3580-956a-11ea-85b1-6291ba54202d.png">

## ..

---
# 5. Error occurs: '_Import error: b.text is not a function. (In 'b.text()', 'b.text' is undefined)_'
<img width="675" alt="image" src="https://user-images.githubusercontent.com/5508226/81886306-57c7b800-956a-11ea-85af-14770dbb5a3b.png">

## ..

---
**System Information:**
 - Roam version: 0.6.1-b214d53f
 - Device: MBPro16
 - OS: macOS 10.15.4
 - Browser Safari 13.1

**Additional context**

This is clearly not ready for prime time. Getting there.

**Comment by micahredding** [comment]
Also have this problem.

**Comment by filipesilva** [comment]
IIRC this is a problem on Safari, but it should work on Firefox and Chrome. We should fix this or present a better error message.

**Comment by panterarocks49** [comment]
Deploying a fix for this today
