### ISSUE TITLE
Cannot connect to my database anymore. The screen hangs in the loading screen forever

### ISSUE THREAD

**Issue by kimoyerr** [Roam-Research/issues#209]
Could not connect to my database all of yesterday and today. The screen is stuck in the loading animation. Any help would be much appreciated!

**Comment by filipesilva** [comment]
Can you try doing a hard refresh? If you're using chrome, that's ctrl+f5.

**Comment by kimoyerr** [comment]
I just removed the cookies as one of the other issues suggested. It is fixed now. Thank you!
