### ISSUE TITLE
Manual links to daily page creates proper daily page if one doesn't yet exist

### ISSUE THREAD

**Issue by houshuang** [Roam-Research/issues#21]
If you create a link to a date page that doesn't yet exist manually (or through a script), and click on it, it will not generate a proper Daily page, but a page with the correct name but a random uid as URL. If you do this for a day in the future, this will break things once that day comes up (normal daily page won't be created). 

Josh promised it would be fixed 20 days ago "in the next version". Not sure what that refers to. Still not fixed. https://roamresearch.slack.com/archives/CTAE9JC2K/p1581570919030600

**Comment by anshbansal** [comment]
The page does show up in Daily notes. But yes the URL is a hash not a proper one

**Comment by houshuang** [comment]
![image](https://user-images.githubusercontent.com/61575/80079476-a0361c00-8550-11ea-9525-b02f84837795.png)

**Comment by panterarocks49** [comment]
I'm not seeing it breaking things, it still adds it to the log for me, which was the change that went up 20 days ago. The URL isn't correct but that shouldn't break anything, log UIDs used to be random. Will fix the UID
