### ISSUE TITLE
Backspace from beginning of line deletes last character of previous line

### ISSUE THREAD

**Issue by notno** [Roam-Research/issues#22]
![roambug01](https://user-images.githubusercontent.com/3149184/80008350-de660980-8484-11ea-8dd7-565f30ba7c71.gif)

You have some bullets:
- a [[thing]]
- |

When your cursor is at the beginning of a bullet and you hit the backspace key, it will delete the last character of the previous line. E.g when my cursor is where the | is in line 2 and i hit backspace, it deletes the last ] of line 1, breaking the link.

It doesn't happen EVERY time, strangely, but it's fairly regular.

I've tested this on Firefox and Chrome on my Windows 10 laptop, and it only happens on Firefox. Has been confirmed by one other Roam user.

**Comment by wilkerlucio** [comment]
Hello, I tried to reproduce the issue but I didn't have success:
![repro-demo-backspace-firefox](https://user-images.githubusercontent.com/25736/80259526-adc7d080-863a-11ea-9dc4-3c49f8cc96df.gif)

I see you are using a custom theme, had you tried using just the standard things? Or maybe you are using some extension on Firefox that may affect it?

**Comment by wilkerlucio** [comment]
Also tried with the brackets hidden, got the same results.
