### ISSUE TITLE
Highlighting blocks and pressing 'delete' navigates browser to previous page

### ISSUE THREAD

**Issue by XVVH** [Roam-Research/issues#220]
When selecting multiple the blocks on a page and pressing the 'delete' button, the blocks are deleted, but the browser navigates back to the previous page (as the 'delete' key also functions as a back button). This issue is intermittent and occurs every few days.

Only occurs when selecting entire blocks - if you are focused and typing in a block, the delete key functions normally (deletes the text behind the cursor)

[Screen recording link](https://streamable.com/8hxn0r) [streamable.com]

**To Reproduce**

1. Navigate to a page in your DB
2. Select multiple blocks
3. Press 'delete' key. Blocks are deleted, but the browser navigates to the previous page

Note: I have not identified what causes this issue to start occurring, but once it starts the browser has to be re-launched for the delete key to function as expected in Roam.

**System Information:**
 - Roam version: 0.6.2-c05aadb4
 - Device: Macbook Pro
 - OS: MacOS 10.15.4 (19E287)
 - Browser Firefox 76.0.1 (uMatrix installed, but disabled for Roam)

**Additional context**
- Does not appear to be related to any new changes, this has been happening for a while.
- Once this issue starts to occur it happens every time. Reloading the page does not resolve the problem.
- Relaunching Firefox resolves the issue consistently
- Have not been able to identify the trigger for this problem, but I experience it every few days.

**Comment by panterarocks49** [comment]
Heya, deploying a fix for this today
