### ISSUE TITLE
password change

### ISSUE THREAD

**Issue by julianhuener** [Roam-Research/issues#228]
I need a settings page where I can change my password of the roam account thanks

**Comment by Stvad** [comment]
you can do it, though it's not obvious - do "reset password" during login and you'd be able to set a new one

**Comment by panterarocks49** [comment]
Make sure your logged out, then visit https://roamresearch.com/#/signin
Here click the forgot your password link
![image](https://user-images.githubusercontent.com/23647837/83962596-719ba880-a853-11ea-8d52-adac10bed2ac.png)

**Comment by Stvad** [comment]
@panterarocks49 people keep being confused about this, I don't think it's a very discoverable solution. IMO this should be exposed as explicit functionality in the "profile" view
