### ISSUE TITLE
Latex support is gone in version 0.6.2-70d5159d

### ISSUE THREAD

**Issue by cmoissar** [Roam-Research/issues#237]
**Describe the bug**

$$ k_B T \rightarrow h \nu $$ now reads, after pressing enter: k_B T \rightarrow h \nu
It used to be formatted.

**To Reproduce**

Enter any math formula between $$ ... $$

**System Information:**
 - Roam version:  0.6.2-70d5159d
 - Device: Desktop computer
 - OS: Ubuntu
 - Browser Chrome

**Additional context**

**Comment by panterarocks49** [comment]
Think this is an issue with loading the component from our server, if this happens to you again try reloading the page

**Comment by panterarocks49** [comment]
Just deployed a change to cache all of our js files from a service worker, latex should load correctly all of the time now. Please reopen if you see this happen again in 0.7.0+
