### ISSUE TITLE
Add slash command for DONE i.e. /DONE => {{[[DONE]]}} 

### ISSUE THREAD

**Issue by drmartell** [Roam-Research/issues#238]
**Describe the problem**

Sometimes I would like to enter tasks that are already completed as a record of what's been done. Presently, I need to enter a TODO and then mark it as DONE. I would like to eliminate a step.

**Feature implementation**

Add slash command for DONE that is analogous to TODO
i.e. /DONE => {{[[DONE]]}}

**Comment by pmbauer** [comment]
on mac, just type `Cmd-Enter` to toggle between todo, done, and no checkbox

**Comment by drmartell** [comment]
> just type `Cmd-Enter` (mac) `Ctrl-Enter` (windows) to toggle between todo, done, and no checkbox

Thank you! Yep, I now see that in the Formatting keyboard shortcuts list.
