### ISSUE TITLE
Roam is using my email in DOM ids.

### ISSUE THREAD

**Issue by VesterDe** [Roam-Research/issues#25]
**Describe the bug**

Roam is using my email in the DOM, for IDs.

![image](https://user-images.githubusercontent.com/722505/80097626-e056c800-856b-11ea-95dd-6bc81b92bc5c.png)

I do not like this. Please stop doing this. This cannot have a rational justification.

**To Reproduce**

Inspect any block.

**System Information:**
 - Device: desktop computer
 - OS: Linux
 - Browser Chrome

**Comment by sambbaron** [comment]
Wow, this is appalling 😲

**Comment by panterarocks49** [comment]
Fix will be in next release (up now if you refresh)
