### ISSUE TITLE
Highlighting in Safari 

### ISSUE THREAD

**Issue by kaizen11** [Roam-Research/issues#253]
Pressing cmd-d in safari hides the safari window 
This is an issue when highlighting in Roam Research 

**System Information:**
 - Roam version: 0.6.2-6d37db15
 - Device: MacBook Air 2020
 - OS: macOS Catalina 
 - Browser Safari

**Comment by panterarocks49** [comment]
We changed the highlight shortcut to `cmd-shift-h` a few weeks ago because of this, `cmd-h` will still work in other browsers
