### ISSUE TITLE
Filter in sidebar not working

### ISSUE THREAD

**Issue by tm5501987** [Roam-Research/issues#261]
**Describe the bug**

The filter menu in the sidebar is not showing any options

![image](https://user-images.githubusercontent.com/64973963/82513376-abd12000-9ac7-11ea-96f6-45d22912b4c2.png)

**To Reproduce**

1. Open a page in the sidebar
2. Click on the filter icon
3. See bug

**System Information:**
 - Roam version: 0.6.2-e4385527
 - Device: Macbook Pro
 - OS: macOS Catalina version 10.15.4 (19E287)
 - Browser: Chrome

**Additional context**

**Comment by panterarocks49** [comment]
Deploying a fix for this today
