### ISSUE TITLE
Editing Table and Database Became Unresponsive

### ISSUE THREAD

**Issue by yosevu** [Roam-Research/issues#263]
**Describe the bug**

I was editing a table and pasted in a block ref. I could no longer edit. Page became unresponsive. I tried reloading and can't access my database. I can access another database, however, so it seems that something happened this specific one.

![image](https://user-images.githubusercontent.com/16216104/82571745-66593500-9b51-11ea-996f-ffc29a93dd34.png)

**System Information:**
 - Roam version: [e.g 0.5.0-43911ff0, find it at the end of the help button pop up]
 - Device: MacBook Pro
 - OS: macOS Catalina
 - Not browser specific (tested in Chrome, Firefox)

**Comment by filipesilva** [comment]
Hmm, I wonder if this is similar to https://github.com/Roam-Research/issues/issues/19#issuecomment-629191389. Can you try the suggestion there?

**Comment by yosevu** [comment]
Yes, deleting the page fixed it for me. Now Daily Notes is loading 🎉
