### ISSUE TITLE
Can't join slackk community

### ISSUE THREAD

**Issue by code-sur** [Roam-Research/issues#266]
**Describe the bug**

Slack invite link is no longer active

**To Reproduce**

![image](https://user-images.githubusercontent.com/3433508/82700773-4014c180-9c45-11ea-8097-ed7fbc78569f.png)
![image](https://user-images.githubusercontent.com/3433508/82700830-5cb0f980-9c45-11ea-8d9c-a4d1c02029ca.png)

**System Information:**
 - Roam version: [roamresearch.com]
 - Device: [desktop computer]
 - OS: [Linux]
 - Browser [FireFox]

**Additional context**

**Comment by filipesilva** [comment]
Heya, thanks for letting us know! Can you try this link meanwhile? https://join.slack.com/t/roamresearch/shared_invite/zt-e8vdhiat-HtNt3Q6nQ8ZkL50qHrzDqQ

**Comment by code-sur** [comment]
Thanks, I did manage to join the slack workspace.
This issue it's about the link in the help massage

**Comment by jacksteamdev** [comment]
@filipesilva The slack link is no longer active, again 😅

**Comment by filipesilva** [comment]
@jacksteamdev sorry about that, updated it in https://github.com/Roam-Research/issues again. 

I think we don't have that original help message anymore though, so it sounds ok to close this.
