### ISSUE TITLE
Subsequent Cmd-K links in a bullet produce incorrect links

### ISSUE THREAD

**Issue by slobizman** [Roam-Research/issues#280]
**Describe the bug**

There is an issue with using Command-K to create an external link, when there is more than one external link in a bullet.  I highlight the text in a note, and then press Cmd-K so I can paste in the URL for it.  For the first link in a bullet it works right: when I Cmd-K, the open and closed parentheses "()" are placed after the text I highlighted and then I do the paste. The result looks like this:  [this is the text](https://www.someurl.com).   But subsequent attempts at Command-K links do not work right, and it places the parentheses around my text, rather than the brackets, and then places brackets in front of my text. After then pasting the URL, it looks like this: [https://www.someurl.com](this is the text). Of course, this results in an incorrect hyperlink.
It seems to happen if there is more than one hyperlink in a bullet.  The first one works fine, but subsequent ones result in the wrong behavior. 

**To Reproduce**

1. Create one link in a bullet.
2. Create a second link in same bullet.

**System Information:**
 - Roam version: 0.6.2-8855b217
 - Device: [e.g. macbook air
 - OS: 10.15.4 (19E287)
 - Browser Chrome

**Additional context**

Others on the Roam channel for Slack have confirmed this bug.

**Comment by keikhcheung** [comment]
Same as #58

**Comment by panterarocks49** [comment]
Deploying a fix for this today, should be up in about 20 minutes
