### ISSUE TITLE
Inline double bracket [[]] search breaks with complex (nested) pages

### ISSUE THREAD

**Issue by classicrob** [Roam-Research/issues#282]
**Describe the bug**

It's almost impossible to find a complex page through an inline double bracket search.

**To Reproduce**

1. Make a nested page, like [[How [[Roam]] knows which blocks are related to each other.]]
2. Try searching for it with double brackets. If you search for two words where one is on each side of [[Roam]], then the page will not pop up. If you search for Roam and any other word within the double brackets, you also won't find the page.

**System Information:**
 - Roam version: 0.6.2-8855b217
 - Device: iPhone X, desktop computer
 - OS: iOS, Catalina
 - Browser: Any

**Additional context**
Below is a recommended solution. Currently, if I have to find one of these complex pages, I have to search for it in the search bar, but because that's not inline like everything else, that makes it so a lot of pages that I thought existed don't pop up in the moment, making it more challenging to effectively link ideas.
- [[]] double brackets search:
    - Make it so the order of words doesn't matter. With pages that have multiple words in the title, if you type them out of order, they won't pop up in the inline search.
    - Make it so symbols like a dash, bracket, or a comma don't matter

**Comment by classicrob** [comment]
I'd love it if there was at least some consistency with the way that it works in the normal search bar

**Comment by classicrob** [comment]
![image](https://user-images.githubusercontent.com/46608303/90338829-9f1a7600-dfa9-11ea-98bf-f85d744583ba.png)
![image](https://user-images.githubusercontent.com/46608303/90338833-a3469380-dfa9-11ea-9435-a409821451e6.png)
![image](https://user-images.githubusercontent.com/46608303/90338835-a80b4780-dfa9-11ea-860e-2d97593f4016.png)

Just illustrating the issue out further

**Comment by classicrob** [comment]
This page is a pain in the butt to find among many other lenses that I have 
![image](https://user-images.githubusercontent.com/46608303/90700234-7eb91880-e242-11ea-8e34-3c78e9309c45.png)

**Comment by classicrob** [comment]
@Bardia95

**Comment by filipesilva** [comment]
Heya, just merged in a fix from @Bardia95 that should address this. Should be available in the next hour or so.

**Comment by classicrob** [comment]
Hey @filipesilva! Thank you so much. Could you also make it so the order of the words doesn't matter? See this example here - it feels very wrong that skipping a few words in adding in the word "capable" pulls up empty results. 
![image](https://user-images.githubusercontent.com/46608303/91179330-9873b900-e6a3-11ea-8e32-1846f490c6a4.png)
![image](https://user-images.githubusercontent.com/46608303/91179345-9b6ea980-e6a3-11ea-9106-71e887496511.png)

**Comment by filipesilva** [comment]
I think that'd be a really good improvement, but would like to separate it from this particular bug. 

Can you open a new issue please? I'd say it's a feature request rather than a bug because - and this is debatable - we don't have that sort of search capability at all for refs so there's no broken implementation to fix. Rather, new functionality must be developed.

**Comment by classicrob** [comment]
@filipesilva Done! Both of these would solve the problem. Either of the below solutions would work, though I would personally opt towards the search bar solution. 

Also, this may just be my naivety towards the code speaking, but block reference (()) search lets you type words in any order. Could something from there be utilized?

[Keyboard shortcut to copy block or page reference from the the search bar and paste into where I was previously typing](https://github.com/Roam-Research/issues/issues/505)
[Make order of words within [[double brackets]] not matter when searching for a page](https://github.com/Roam-Research/issues/issues/504)

**Comment by filipesilva** [comment]
Something could be used from one on another I think, probably with a loss of performance. I'm not too sure of what the original reasoning was for the difference so would have to check that.
