### ISSUE TITLE
Redundant Keywords

### ISSUE THREAD

**Issue by mafsi** [Roam-Research/issues#298]
**Describe the problem**
I use synonymy when I add keywords to my knowledge for example: time / temporality / chronology / duration. Sometimes I'm not thinking of time, but duration or chronology or temporality. I can give you more examples of grouped keywords in order to see the idea:
absurdity / nonsense
loss / lack / absence / emptiness
money / economy / capitalism etc.

**Feature implementation**

I would like that a page like> time / temporality / chronology / duration to pull up all the knowledge where time or temporality or chronology or duration exist

**Comment by houshuang** [comment]
@mafsi You could easily use a query to do this.

**Comment by mafsi** [comment]
> 
> 
> @mafsi You could easily use a query to do this.

Please explain with an example

**Comment by houshuang** [comment]
{{[[query]]: {or: [[money]] [[economy]] [[capitalism]]}}}

**Comment by mafsi** [comment]
> {{[[query]]: {or: [[money]] [[economy]] [[capitalism]]}}}

Is not showing all the possible linking references unless I click Money, Economy, Capitalism in the querry. But this is sending me to an individual page: Money, or economy etc. 
I want to stay on the page: Money / Economy / Capitalism and see all the related references that contain words money, economy, capitalism

**Comment by mafsi** [comment]
> 
> 
> Maybe you need to change capitalization of links? Example
> 
> ![image](https://user-images.githubusercontent.com/61575/84011979-25e21f80-a977-11ea-977a-0c4b9132a13f.png)

Ok, is working now, but I still think that some pages are redundant like money, economy, capitalism 
Querry is good if you want to write an article and have all info pulled out from **existing pages**, that were **previously linked**.
