### ISSUE TITLE
Hashtag-based link syntax does not support international characters

### ISSUE THREAD

**Issue by teodorlu** [Roam-Research/issues#3]
**Describe the bug**

Hashtag-based link syntax does not support international characters.

German, Russtian and emoticon-based (by Ralf Westphal):
![image](https://user-images.githubusercontent.com/5285452/79872806-8973b600-83e6-11ea-9e69-43d302a399b6.png)

Norwegian (by me):

![image](https://user-images.githubusercontent.com/5285452/79872857-9abcc280-83e6-11ea-9225-af6031b4f0c9.png)

**To Reproduce**

1. Try to create a hashtag-link where the link contains international characters
2. Watch the link cut off before the first international character

**Additional context**

From Slack: https://roamresearch.slack.com/archives/CN5MK4D2M/p1582801515145800

**Comment by teodorlu** [comment]
Workaround: use a hashtag _and_ brackets: `#[[eksempel/høy-viktighet]]`

Suggested by Conor on Slack to the report.

![image](https://user-images.githubusercontent.com/5285452/79873275-33ebd900-83e7-11ea-876f-042ea30001a7.png)

**Comment by teodorlu** [comment]
Another advantage of the hashtag _and_ bracket syntax is that it supports spaces. This is really great.

![image](https://user-images.githubusercontent.com/5285452/79950099-d56e3b80-8476-11ea-8d3b-c6e3ea126fa0.png)

Personally, I consider this a solved problem, then. I am able to write any link, and it shows the tag without grabbing attention.

I'm still choosing not to close this issue, because I think it makes sense to have proper i18n support in a heavily text-based product. Perhaps more relevant when we get closer to a non-beta release.

**Comment by panterarocks49** [comment]
We just deployed a fix for international characters in tags, can you verify it's working for you now? (might have to reload page first)

**Comment by teodorlu** [comment]
![image](https://user-images.githubusercontent.com/5285452/80186935-17ca8080-860f-11ea-8875-b6e96bc4e12f.png)

Looks good. Thanks!

I consider this issue resolved.
