### ISSUE TITLE
Deleting a Page

### ISSUE THREAD

**Issue by mabobakr86** [Roam-Research/issues#305]
**Cannot Delete Pages**

I experiment with roam on a daily basis, so i am creating pages and delete pages, Today i tried to delete all my pages one by one from the pages tab as i always do one by one, but i realized that there exist two pages that wont delete despite trying everything.

**Video showing the issue**
[video.zip](https://github.com/Roam-Research/issues/files/4725126/video.zip)

**System Information:**
 - Roam version: 0.6.2-a36ec4c4
 - Device: Laptop
 - OS: Ubuntu 20.04 LTS
 - Browser: Firefox, Chrome

**Comment by jsscharf** [comment]
Same problem here this morning.

**Comment by panterarocks49** [comment]
Can you post a screenshot of any errors in the developer console?

**Comment by mabobakr86** [comment]
i can't test it anymore.

**Comment by palashkaria** [comment]
I get this in the console while trying to delete a page 

I was unable to add more blocks to the page, so I tried deleting it, but it did not work


@panterarocks49 
```
ERROR [relemma.fire.link.core:263] - [DEFAULT] - error while applying confirmed tx to server-conn #error {:message "Cannot store nil as a value at [:db/add 4485 :block/uid nil]", :data {:error :transact/syntax, :value nil, :context [:db/add 4485 :block/uid nil]}}
```
![image](https://user-images.githubusercontent.com/2976363/85404488-9f376000-b57c-11ea-8285-cef33de6f912.png)
