### ISSUE TITLE
If you start any search with a space (e.g. " word"), Roam freezes/crashes

### ISSUE THREAD

**Issue by Lunariz** [Roam-Research/issues#307]
**Describe the bug**

I was searching for a short word ('Ping') and found that I was unable to search for exact matches only, getting results like "jumping", "stopping" and "developing".
In an attempt to enforce the exact search, I prepended a space, such that the search query showed " ping". This freezes/crashes Roam

**To Reproduce**

1. Go to All Pages
2. Focus the search box: Search All Pages
3. Enter any normal word
4. Go to the beginning of the word and prepend a space
5. Roam crashes

**System Information:**
 - Roam version: 0.6.2-a36ec4c4
 - Device: Desktop computer
 - OS: Windows
 - Browser: Chrome

**Additional context**
Relatedly, I'd love for more control over search. When searching the word 'ping' I'd like to tick a checkbox for 'exact match' so that I don't get results for "jumping", "stopping", "developing" etc.
It seems like something similar is needed for 'link unlinked references' also.

**Comment by panterarocks49** [comment]
Deploying a fix for this now, will be up in a few minutes
