### ISSUE TITLE
Ctrl/Cmd + J/K do not work in the search box

### ISSUE THREAD

**Issue by tclaiborne** [Roam-Research/issues#312]
When doing a search (using Ctrl/Cmd + U), you cannot navigate the search results with Ctrl + J/K as you can everywhere else in Roam. 

Both Ctrl + J and K get sent to the browser as regular commands (in Chrome this opens Downloads for Ctrl + J and Ctrl + K focuses on the browser's search box).

**Comment by panterarocks49** [comment]
Pushing up a fix for this now
