### ISSUE TITLE
Markdown links with URLs containing brackets are parsed incorrectly

### ISSUE THREAD

**Issue by jarmitage** [Roam-Research/issues#313]
Example:

```
[OSC Protocol](https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Generic-Tools-Protocols/Open-Sound-Control-(OSC).md)
```

Result:

![Screenshot 2020-06-06 at 16 21 01](https://user-images.githubusercontent.com/2885827/83947893-bc94cc00-a811-11ea-9ab0-02373da0c6db.png)

Furthermore it produces the broken link:

```
https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Generic-Tools-Protocols/Open-Sound-Control-(OSC).md)
```

**Comment by tkwa** [comment]
I already submitted this issue: https://github.com/Roam-Research/issues/issues/186

**Comment by jarmitage** [comment]
Thanks @tkwa didn't see that!
