### ISSUE TITLE
Code Blocks for new roam/css feature take a LONG time to render when expanding

### ISSUE THREAD

**Issue by GitMurf** [Roam-Research/issues#314]
**Describe the bug**

See details on this Slack thread. @filipesilva was involved so has some context to it already but wanted me to create an Issue here.

https://roamresearch.slack.com/archives/C011BV1218F/p1591294957043000

With the new roam/css method with the code and if you go in to try and "view the code" in Roam by expanding the bullet that the CSS is pasted into, there is extreme lag/slow loading? It takes about 20-30 seconds to show/render the CSS in the Roam code block for @jmharris903 [Railscast-for-Roam-Research-Theme](https://github.com/jmharris903/Railscast-for-Roam-Research-Theme) theme.

This theme is ~3,000 lines long (although half of it is /* */ comments). Conor mentioned on Twitter it is probably the time it takes for the code block to translate/render the code into its syntax highlighting/color.

This GIF shows the issue with the code block and also the same code in a plain text regular block and having zero lag.

![Issue with roam css code block taking a long time compared to instant plain text](https://user-images.githubusercontent.com/64155612/83980264-1c01e300-a8c9-11ea-9d03-bec7ea96ce7d.gif)

**System Information:**
 - Roam version: 0.6.2-159ca1a7
 - Device: laptop (i7 16 gb ram, quad core)
 - OS: windows 10
 - Browser: Chrome

**Additional context**

Here is some extra stuff from our conversations on Slack...

> I thought you were onto something that would at least explain it, but look at this GIF. I pasted the exact same 3,000 lines of text into a plain block/bullet and zero lag collapsing/expanding. And then 20+ seconds when I expand the triple ` code block. So it must be at least partially with the Code Block rendering combined with large block.

> I was experimenting with this theme (which was my default) and others via the roam/css method and had the same issue you did but had no further apparent impact beyond that (though I have not tried logging off and on since). I found the shorter length themes to be faster in doing the initial load

> maybe this will help you in troubleshooting. It seems to be the Code block rendering large text blocks as a plain text block of same text has zero lag. I think it might be Codemirror just taking it's time to do the rendering and syntax highlighting.

**Comment by filipesilva** [comment]
cc @panterarocks49

**Comment by panterarocks49** [comment]
CodeMirror has pretty bad performance when rendering a whole document. Deploying a fix to limit the size of CodeMirror to 1000px, so it won't render the whole document. This should fix the performance problems.

**Comment by hugozap** [comment]
Did something change recently? I'm having this issue with code blocks taking a long time to update and no visible indicator that changes are not saved yet (So if I write something, wait 10 seconds and leave the page, the changes are lost. If I wait like 40 seconds they get saved)
