### ISSUE TITLE
Help database not loading for some users

### ISSUE THREAD

**Issue by sellaro** [Roam-Research/issues#325]
**Describe the bug**
While loading Roam help database, the browser gets stuck on the Roam loading logo. I could reproduce in Firefox and Chrome in Windows box, Fireforx and Chrome in a Linux box, Chrome in a Mac box, and Chrome in an Android phone (all connected via the same wi-fi network). The bug was also reproduced in the Android phone using chrome in a different (carrier) network. For all these boxes, I cleared browsing data and used incognito mode to no avail.

**To Reproduce**

1. Clear Browsing Data in Chrome
2. Load https://roamresearch.com/
3. Scroll down to the bottom and click any of the Roam Research section links
4. See bug

**System Information:**
 - Roam version: [e.g 0.5.0-43911ff0, find it at the end of the help button pop up]
 - Device: Android (Chrome 83.0.4103.96), Windows 10 (Chrome 83.0.4103.97), Linux Ubuntu 20.04 LTS (Chrome 83.0.4103.61 (Official Build) (64-bit); Firefox 77.0.1 (64-bit))
 
**Additional context**
User: login@sellaro.co

**Comment by sellaro** [comment]
Update: I was also able to reproduce on Linux Ubuntu 20.04 LTS running Brave Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by pmbauer** [comment]
From what I can see in the dev console
* accessing the help db while logged in is fast; for my account, the firebase websocket hits `s-usc1c-nss-204.firebaseio.com`
* accessing the help db from an incognito window or via tor (with vpn and without) never loads; the firebase websocket always `hits s-usc1c-nss-255.firebaseio.com`; my guess is this has something to do with the sharding scheme?

This might explain why so many users trying to try out roam via the help graph sandbox can't access anything but all the developers can.

**Comment by filipesilva** [comment]
Heya, we have a fix for this being reviewed. After we close this issue, a fix should be available in ~20m.

**Comment by filipesilva** [comment]
A workaround for now is to log in via the main page https://roamresearch.com/ before loading the other databases.
