### ISSUE TITLE
Page filtration doesn't work on sidebar pages

### ISSUE THREAD

**Issue by classicrob** [Roam-Research/issues#326]
**Describe the bug**

![image](https://user-images.githubusercontent.com/46608303/84069833-639b7400-a988-11ea-9e76-5f14ed044299.png)

**To Reproduce**
Open a page in the sidepar and attempt to do page filtration on it. Works in the main view, doesn't work in the sideview. To be clear, I'm referring to page filtration, not linked references filtration

**System Information:**
 - Roam version: 0.6.2-3bc334b3
 - Device: Desktop Computer
 - OS: Mac
 - Browser: Chrome

**Comment by panterarocks49** [comment]
I think we pushed up a fix for this in the past month, it seems to be working for me now on 0.7.0 version and above. Reopen if still an issue
