### ISSUE TITLE
Undo on text styles always results in 2 chars shifted to the right in text selection

### ISSUE THREAD

**Issue by keikhcheung** [Roam-Research/issues#345]
**Describe the bug**

After applying basic text styles like `**bold**`, `__italic__`, `~~strikethrough~~` or `^^highlight^^`, pressing `Cmd` + `Z` for undo, the original selection of text is shifted by 2 characters to the right.

It is particularly annoying when you want to undo the style _and then_ write something right away.

![Roam-undo-bug-1](https://user-images.githubusercontent.com/22561336/84567741-e488b000-ad7a-11ea-8554-f621c4ae2e7b.gif)

![Roam-undo-bug-2](https://user-images.githubusercontent.com/22561336/84567743-e81c3700-ad7a-11ea-92f7-6421b5695e1a.gif)

![Roam-undo-bug-3](https://user-images.githubusercontent.com/22561336/84567745-ece0eb00-ad7a-11ea-8962-4f08fd2c2dbb.gif)

**To Reproduce**

1. Highlight some texts.
2. Apply bold, italic, strikethrough or highlight with shortcuts.
3. Undo with shortcut.
4. See bug.

**System Information:**
 - Roam version: 0.6.2-644d9e75
 - Device: MacBook Pro
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome, Firefox

**Comment by panterarocks49** [comment]
Have a fix for this in an open PR, will close when it's deployed
