### ISSUE TITLE
Could not import JSON or Markdown into new Roam graph.  

### ISSUE THREAD

**Issue by Thomas235-dev** [Roam-Research/issues#347]
**Describe the bug**
I exported selected notes from my initial Roam graph to re-import into a new Roam graph.  I tried both JSON and Markdown files.  

I receive the following error when I try to re-import 1 or more of the exported files, regardless if it was JSON or Markdown.  I am running in Safari on a MAC. 

_**Import error: b.text is not a function. (In 'b.text()', 'b.text' is undefined)**_

**To Reproduce**

**Steps to reproduce the behavior:**
1. Go to '...' at top right of Roam screen
2. Click on 'Import Files'
3. Select either a JSON or Markdown file that was exported from Roam
4. See bug

**System Information:**
 - Roam version: 0.6.2-644d9e75
 - Device: [2016 MacBook Pro]
 - OS: [macOS Catalina Version 10.15.5 ]
 - Browser [Safari]

**Additional context**

**Comment by panterarocks49** [comment]
Same as https://github.com/Roam-Research/issues/issues/206, closing in favor of that thread
