### ISSUE TITLE
Roam updates break the date picker

### ISSUE THREAD

**Issue by mmower** [Roam-Research/issues#349]
**Describe the bug**

Almost every time I come to use the date picker it spins for several seconds then won't load. I then have to reload the page and lose my sidebar. I am getting pretty annoyed by this.

To be clear: my point is not that I don't want Roam to update. But that there are more or less annoying places for my workflow to be interrupted. For example, starting a new daily page is likely a good place but half-way through a meeting where I am taking notes and need to reference a date, having to reload and lose all my Roam context is not.

**To Reproduce**

Come back tomorrow and try to use the date picker.

**System Information:**
 - Roam version: 0.6.2-d4f7795f
 - Device: MacBook Pro 15,3
 - OS: macOS 10.14.6
 - Browser: Chrome 83.0

**Additional context**

**Comment by filipesilva** [comment]
Heya, this is the same as https://github.com/Roam-Research/issues/issues/45 right?

**Comment by mmower** [comment]
Yep, forgot I already filed this. Still annoying as hell!

**Comment by filipesilva** [comment]
As it happens, I'm actually looking at ways to prevent it right now. Will keep people posted on #45 as things move forward.
