### ISSUE TITLE
Don't create image of text copied from OneNote unless necessary

### ISSUE THREAD

**Issue by bjfinn** [Roam-Research/issues#357]
When copying plain text from OneNote, Roam additionally inserts an image of the original. This seems pointless and the user has to delete it.

Presumably the image is useful if the original included features that Roam doesn't support, but for plain text presumably it is not useful.

So, preferably Roam should only create the image if the material copied contains something Roam might not import correctly/at all.

**Comment by Bardia95** [comment]
Hi @bjfinn we just fixed this in a new release, so closing this issue!
