### ISSUE TITLE
Change the C-c C-x chord sequence for showing edit avatars

### ISSUE THREAD

**Issue by antonylewis** [Roam-Research/issues#362]
**Describe the bug**

Ctrl-c Ctrl-x is too common a sequence of keystrokes for toggling Edit Icon / Avatars.  This results in people showing avatars and they don't know how to turn them off.  Recommend assigning a less commonly typed sequence.

**To Reproduce**

1. Press Ctrl-c Ctrl-x
2. Go to the Roam Slack and ask how to get rid of the little icons that have appeared everywhere.

**Comment by panterarocks49** [comment]
Deploying a fix today
