### ISSUE TITLE
User email is overflowing the layout.

### ISSUE THREAD

**Issue by mlemos** [Roam-Research/issues#367]
**Describe the bug**

The user email is breaking the design.
It is overflowing the sidebar.

<img width="677" alt="Screen Shot 2020-06-22 at 9 06 38 AM" src="https://user-images.githubusercontent.com/29751/85286440-0cf26780-b469-11ea-92a5-b3da54ca1112.png">

**To Reproduce**

Just open Roam with a user email big enough.

**System Information:**
 - Roam version: Version 0.6.3-8db64626
 - Device: MacBook Pro
 - OS: MacOS 10.15.5
 - Browser Chrome (using it as shortcut opened as a window)

**Comment by panterarocks49** [comment]
Heya, we deployed a fix for this the other day
Should look like this now

![image](https://user-images.githubusercontent.com/23647837/87491812-ee156a00-c5fd-11ea-8808-d2faa6687850.png)

Email is in the dropdown

**Comment by mlemos** [comment]
Awesome! Thanks!
