### ISSUE TITLE
Sidebar CSS overflow

### ISSUE THREAD

**Issue by rohanraval** [Roam-Research/issues#369]
Database name and email in the sidebar go beyond the sidebar margin.

<img width="775" alt="Screen Shot 2020-06-23 at 9 13 51 PM" src="https://user-images.githubusercontent.com/16498354/85485626-1aa60b00-b597-11ea-9883-112aa765ad8c.png">

**System Information:**
 - Roam version: 0.6.3-625ab517
 - Device: Laptop
 - OS: MacOS 10.15.5
 - Browser: Chrome

Fyi, I am _not_ using any CSS themes, this is just out-of-the-box Roam. It only started popping up today, haven't seen this before.

**Comment by anaxios** [comment]
Having the same issue. Same out-of-the-box.

**Comment by panterarocks49** [comment]
Deployed a fix for this a few days ago, Should look like this now
![image](https://user-images.githubusercontent.com/23647837/87378243-425b1400-c542-11ea-9181-cebf95ac599c.png)
