### ISSUE TITLE
hotkey for strikethrough on windows

### ISSUE THREAD

**Issue by pconerly** [Roam-Research/issues#380]
**Describe the problem**

I'd like a hotkey for strikethrough on windows. I'm using a page on Roam to play [Thousand Year Old Vampire](https://timhutchings.itch.io/tyov) and it involves striking out a lot of things.

**Feature implementation**

`Ctrl-Y` seems like it'd be good for windows (similar to the strikethrough hotkey `cmd-y` on mac) however `ctrl-Y` is bound to "redo".

This is a change, but I'd propose:
`Ctrl-Shift-z`: becomes redo (which is typical in most apps!)
`Ctrl-y`: becomes strikethrough

**Additional context**

A bug related to this, if I pull up the `/` autocomplete menu and type "Strikethrough", I see that it suggests that hotkey `Ctrl-Y`

**Comment by cericoda** [comment]
+1 on remapping the undo in windows as you described!

Ctrl-y is very hard for me to remember for redo, it's usually ctrl+shift+z or ctrl+r, in fact searching this github and finding this issue helped me work out the correct key!

**Comment by panterarocks49** [comment]
We've had some issues getting `ctrl-shift-z` to work on some systems so that's why `ctrl-y` exists

I think windows-key + y is the current shortcut on windows for strikethrough, we don't advertise it because I never tested if it works on windows, but it used to work for me on ubuntu

**Comment by pconerly** [comment]
@panterarocks49 thanks for the response!

`win-y` works for me on Windows 10 & Chrome, thanks for the workaround info! (If you'd like me to test any other browsers LMK.)

I'd still advocate the `ctrl-shift-z` combo. This is totally anecdotal, but I did web-dev for a website that had a few three-key hotkeys. We used [redux-saga](https://redux-saga.js.org/) and were able to handle hotkeys pretty nicely with it. but YMMV.

**Comment by panterarocks49** [comment]
Yeah, tbh the `ctrl-shift-z` issue could have just been my computer's problem, it also didn't work for me on other applications

Will keep this open until that's resolved

**Comment by MaskyS** [comment]
Windows shortcut for Strikethrough has been updated to `Ctrl+Y`, thanks all for suggestions.

**Comment by MaskyS** [comment]
(redo shortcut has similarly been updated)
