### ISSUE TITLE
Date Picker regularly stops working and bugs other functionality

### ISSUE THREAD

**Issue by Lunariz** [Roam-Research/issues#39]
**Describe the bug**

It's unclear when this bug triggers, but when it does, the {{date}} picker will show a spinning circle.
If this occurs, it will bug other functionality. For example, going to the Graph View after having this bug will usually crash Roam.

**To Reproduce**

1. Bug usually appears when Roam has been open a long time
2. Type /date to add the {{date}} picker
3. Note the calendar does not appear, instead you see only the spinning circle

**System Information:**
 - Device: Desktop Computer
 - OS: Windows
 - Browser: Chrome

**Comment by Lunariz** [comment]
This specific instance of the bug may have been caused by the temporary server outage. I'll comment here if it happens again.

**Comment by filipesilva** [comment]
Heya, marking this as a duplicate of https://github.com/Roam-Research/issues/issues/45 just because that one has some more context on it.
