### ISSUE TITLE
Kanban board should respect filters

### ISSUE THREAD

**Issue by steveklabnik** [Roam-Research/issues#394]
**Describe the problem**

I'd like to start using Kanban boards, but when i filter todos on a page, the filters aren't respected in the kanban board.

**Additional context**

Here's a screenshot to show what I mean:

![image](https://user-images.githubusercontent.com/27786/86268894-8b988480-bb8e-11ea-9e38-28d7be9c83c8.png)

the tasks themselves are filtered properly, but the kanban board still shows all tasks.

**Comment by panterarocks49** [comment]
deploying a fix for this tonight
