### ISSUE TITLE
Image upload from #quick-notes is not working

### ISSUE THREAD

**Issue by JohanCodinha** [Roam-Research/issues#408]
Uploading an image to roam from quick-notes or full-site interface on Safari mobile is not working.
After selecting the images from the OS image picker nothing happen.

At least one other users is experiencing the issues based on subreddit post.

**To Reproduce**

Steps to reproduce the behaviour:
1. Open roam on safari mobile
2. Select upload image from / dropdown
3. Select image from phone library

**System Information:**
Safari mobile iOS 12.4.6

**Comment by jmjones1118** [comment]
Same issue with Chrome. 
iPad 10.5
Running iOS 13.5.1

**Comment by panterarocks49** [comment]
Deploying a fix for this today

**Comment by JohanCodinha** [comment]
Just to let you know the issue is still present.
The ui freeze for some ms after selecting a picture then nothing happens.
Maybe look into using a web worker to process the images, otherwise you get ui block and safari will drop the process.

**Comment by joshytsmithy** [comment]
I've found a fix for this... (Will help dev know what issue is too). 

After trying to upload, go to full site on mobile and there is a pop up warning of the public link. 

Click "don't show again". 

Quick capture will now allow image upload.
