### ISSUE TITLE
Clicking checkbox that's not at the start of a bullet does nothing

### ISSUE THREAD

**Issue by woodenflute** [Roam-Research/issues#410]
**Describe the bug**

Having something like this
- Something with a checkbox {{TODO}}
creates a checkbox, but it's not possible to checkmark it.

**To Reproduce**

1. In any bullet
2. Create a {{TODO}} that's not at the start of the bullet
3. Try to checkmark it

**System Information:**
 - Roam version: 0.7.0-1e60710c
 - Device: Macbook Pro 2020
 - OS: MacOS Catalina 10.15.4
 - Browser: Chrome

**Comment by panterarocks49** [comment]
I can't reproduce this on `0.7.3-3749cce3`. I think we pushed up changes to the checkboxes that fixed this recently, but not sure if was directed at this issue exactly. Is this still an issue for you on the latest version?

**Comment by woodenflute** [comment]
@panterarocks49 It seems like it's not an issue any more. Thanks!
