### ISSUE TITLE
Check for updates unresponsive

### ISSUE THREAD

**Issue by Bardia95** [Roam-Research/issues#424]
**Describe the bug**

The check for updates button is unresponsive. One user and myself have reported this issue. Reloading does not seem to help. It did work for me in Chrome and Safari but not in Chrome app (macOS Big Sur and Catalina)

**To Reproduce**

1. Click "Check for updates" button
2. Click "Click here to update"

**System Information:**
 - Device: Macbook
 - OS: macOS 10.14.6 
 - Browser Chrome 83.0.4103.116

**Comment by opie4624** [comment]
@Bardia95 Thanks for creating this issue. To add some details to my initial report. It does appear to be limited to the Chrome App. As a workaround, you can open Roam in a browser tab, apply the update, then hit reload in the chrome app. (I'm guessing this is updating the "upgradable" assets in the local browser storage, which the chrome app shares.)

**Comment by panterarocks49** [comment]
What version are you on/were you on when this happened?
We had a bug with updates prior to 0.7.2, should be fixed now in 0.7.2.
Another fix for this is to close all Roam tabs and reopen

**Comment by panterarocks49** [comment]
Nevermind, was able to reproduce on 0.7.2-ac00723f

**Comment by mwickens** [comment]
I have the same issue with the Edge app.

**Comment by nikhilmaddirala** [comment]
Same issue on macOS Catalina / Safari.
