### ISSUE TITLE
Quick Capture is only syncing one block

### ISSUE THREAD

**Issue by lawrebel** [Roam-Research/issues#43]
If I add two tweet links (two blocks) to the Quick Capture, then only the first tweet link block is synced between an Android phone and Windows desktop. I cannot collapse the synced tweet on the desktop unless I return a node after it. The un-synced block is deleted completely.

Android to
Windows 10/desktop
Chrome

**Comment by filipesilva** [comment]
@lawrebel does this always happen for you?

**Comment by filipesilva** [comment]
Will close then, let me know if it starts happening again.
