### ISSUE TITLE
Blocks appear duplicated

### ISSUE THREAD

**Issue by filipesilva** [Roam-Research/issues#44]
**Describe the bug**

Blocks can appear duplicated across parents. Editing a block will alter all of the duplicated blocks.

Slack user `Dhvani` captured it happening: https://drive.google.com/open?id=1PyNCNfC3IkmfOPE3uj6md5hS23lI1Jnu

**To Reproduce**

No consistent reproduction yet :/

**System Information:**
 - Device: desktop computer
 - OS: OSX
 - Browser: Chrome

**Additional context**

I think this might be related to other reports of missing or moved blocks, but am not sure.

**Comment by ricalamino** [comment]
I have a duplicated block... But it has a special character. Its name is "Psicanálise"

![image](https://user-images.githubusercontent.com/36570/80608298-f0a7f080-8a0c-11ea-9e46-66cdfafd0570.png)

![image](https://user-images.githubusercontent.com/36570/80608330-fbfb1c00-8a0c-11ea-851f-a7d2a3d513b4.png)

![image](https://user-images.githubusercontent.com/36570/80608368-0c12fb80-8a0d-11ea-9999-02da7c16af96.png)

**Comment by scribu** [comment]
I've also encountered this issue of duplicate blocks. Still happens even after I reload the browser page.

Device: desktop computer
OS: OSX
Browser: Firefox

**Comment by scribu** [comment]
Observed behaviour:

1. Copy-Pasted several block from Notion.
2. Started editing the nodes.
3. The nodes reverted to the initial state.

**Comment by filipesilva** [comment]
Heya, I'm closing this in favor of https://github.com/Roam-Research/issues/issues/201. It's the same thing, but I added some newer information there and there's a nice gif from the author too.
