### ISSUE TITLE
Roam/js block stops roam loading on all platforms, cannot recover

### ISSUE THREAD

**Issue by jacrify** [Roam-Research/issues#447]
**Describe the bug**

I added a roam/js block that contained the following code:
`var r={a:1};`  

So it turns out that r is a reserved global variable, and now roam will not load on any of my devices. I cannot turn off the roam/js block or delete the page (called "test" in my db).

Please help recover.

I have many messages on load such as:

main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:2239 Uncaught TypeError: r.vd is not a function
    at zC (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:2239)
    at VO (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:3173)
    at $O (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:3174)
    at e (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:3218)
    at Function.f [as vd] (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:3220)
    at bN (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:3063)
    at main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:3220
    at PCa (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:3045)
    at MessagePort.<anonymous> (main.js?__WB_REVISION__=e4fef55e772e9e0866190d48cf3a12a3:1394)

If applicable, add screenshots to help explain your problem. You can paste them in here and they will be uploaded automatically.

If you have a video of you experiencing the bug, that is also super helpful!

**To Reproduce**

4. See bug

**System Information:**
 - Roam version: [e.g 0.5.0-43911ff0, find it at the end of the help button pop up]
 - Device: [e.g. iPhone6, desktop computer]
 - OS: [e.g. iOS8.1, Windows, ]
 - Browser [e.g. Chrome, Safari, FireFox, Brave]

**Additional context**

**Comment by jacrify** [comment]
Fixed. 

I searched source for "roam/js", set up a breakpoint just after the bit that was setting up the routes, and overrode the route variable just afterwards so roam stopped interpreting scripts. IE: 

u0 = new x("roam","js","roam1/js",1767129628)  

Then once roam loaded I deleted the page containing the fauly block.

**Comment by huylenq** [comment]
Would be nice to have a "safe mode" feature (turning on by an URL query flag perhaps?) to disable loading of all roam/js blocks.

**Comment by jacrify** [comment]
Roam team have added option to disable roam/js: add  "?disablejs=true" to the end of your url

**Comment by pmbauer** [comment]
@jacrify thanks; where was this announced?

**Comment by jacrify** [comment]
It was on slack in a thread. Figured it was obscure so posted here.

**Comment by pmbauer** [comment]
Roam team are lucky to have such a strong community running comms for them ;)
Thanks for letting us know
