### ISSUE TITLE
Date picker stops working suddenly

### ISSUE THREAD

**Issue by mmower** [Roam-Research/issues#45]
**Describe the bug**

The datepicker will suddenly stop working giving:

    Date picker Failed to Load. Try reloading your page. 

I'm not sure there is a way of reproducing this but understand from @filipesilva that it might be related to deployment of a new fix.

**System Information:**
 - Device: MacBook Pro 15,3
 - OS: macOS 10.14.6
 - Browser: Chrome 81.0

**Comment by filipesilva** [comment]
To speed up app load we divide the app code into several parts, and only load it as needed. The datepicker is one of them. Whenever we deploy a new version of the app, the parts that haven't been loaded yet are no longer reachable. This means that pages that are still open won't be able to load these anymore.

We were looking at a couple of ways of addressing this. Using a service worker and preloading the assets was the most promising, because it was also on the path to having a full offline working PWA.

cc @panterarocks49

**Comment by anshbansal** [comment]
I faced this today. 

I accidentally closed my browser window. Not the tab but the whole browser. I reopen it and clicked Command + Shift + T (on Mac) to re-open closed tabs which opened roam tab also. After that I started typing and noticed that typing /date showed a white rectangular box (like a text input). When I clicked on the white box the date picker showed up. But when I clicked on the date nothing happened.

So I decided to refresh the tab after the dot showed everything is synced. After the refresh happened date picker started working again. But I noticed that I had lost some data. So maybe the above steps are relevant to #42 also

**Comment by Nateliason** [comment]
Just hit this issue today, not able to get it to load.

**Comment by RobinAllenson** [comment]
Same for me. I've had this issue a couple of time over the last two days. I see different weirdness:
- Sometimes the date picker just doesn't load
- Sometimes upon syncing that line dies, or reappears once I deleted it
- Once I've already chosen a date, sometimes the above bugs appear upon reloading

**Comment by mmower** [comment]
To be clear: my point is not that I don't want Roam to update. But that there are more or less annoying places for my workflow to be interrupted. For example, starting a new daily page is likely a good place but half-way through a meeting where I am taking notes and need to reference a date, having to reload and lose all my Roam context is not.

**Comment by panterarocks49** [comment]
Just deployed a change to cache all of our js files from a service worker, the date picker should load correctly all of the time now. Please reopen if you see this happen again in 0.7.0+
