### ISSUE TITLE
[Export/Import] Node Collapse State is Not Preserved

### ISSUE THREAD

**Issue by pmbauer** [Roam-Research/issues#452]
**Describe the bug**

When importing a previously JSON-exported graph, all nodes are collapsed by default and not preserved.

1) Defaulting to an expanded state would be a better default
2) preserving the expand/collapsed state would be ideal

**To Reproduce**

1. Import any previously exported graph that contains nested blocks
2. Observe all nodes are imported collapsed

**System Information:**
 - Roam version: all
 - Device: all
 - OS: all
 - Browser: all

**Additional context**
Export/Import related bugs
* [Block-Level Back-References Are Not Preserved](https://github.com/Roam-Research/issues/issues/451)
* [Node Collapse State is Not Preserved](https://github.com/Roam-Research/issues/issues/452)
* [View As State Is Not Preserved](https://github.com/Roam-Research/issues/issues/453)
* [Filters Are Not Preserved](https://github.com/Roam-Research/issues/issues/454)
* [Nodes with Versions are Not Preserved](https://github.com/Roam-Research/issues/issues/455)

**Comment by filipesilva** [comment]
Should be fixed with the "Restore graph" option, please see https://github.com/Roam-Research/issues/issues/451#issuecomment-718800530 for details.
