### ISSUE TITLE
[Export/Import] Nodes with Versions are Not Preserved

### ISSUE THREAD

**Issue by pmbauer** [Roam-Research/issues#455]
**Describe the bug**

When importing a previously JSON-exported graph, versions of nodes are lost.
It does not appear this feature is part of the export.

**To Reproduce**

1. Export any graph that contains versions
2. Observe that the versioned nodes are absent from the export

**System Information:**
 - Roam version: all
 - Device: all
 - OS: all
 - Browser: all

**Additional context**
Export/Import related bugs
* [Block-Level Back-References Are Not Preserved](https://github.com/Roam-Research/issues/issues/451)
* [Node Collapse State is Not Preserved](https://github.com/Roam-Research/issues/issues/452)
* [View As State Is Not Preserved](https://github.com/Roam-Research/issues/issues/453)
* [Filters Are Not Preserved](https://github.com/Roam-Research/issues/issues/454)
* [Nodes with Versions are Not Preserved](https://github.com/Roam-Research/issues/issues/455)

**Comment by filipesilva** [comment]
Should be fixed with the "Restore graph" option, please see https://github.com/Roam-Research/issues/issues/451#issuecomment-718800530 for details.
