### ISSUE TITLE
Chrome App Won't Install

### ISSUE THREAD

**Issue by Bardia95** [Roam-Research/issues#459]
**Describe the bug**

User reset to the default Chrome settings, and now, when he clicks on the Roam desktop icon, it doesn't open Roam. Instead, it opens Chrome and he is no longer able to use Roam on the desktop.

Chrome is not letting the Roam App install. The Roam App shows that it wants to be installed, but it won't work when the user clicks on Install. (See the screenshot attached). User tried multiple approaches: deleted Chrome history, deleted Chrome passwords, etc., but no luck.

![CleanShot 2020-07-30 at 12 13 44](https://user-images.githubusercontent.com/24982590/88947154-23f15a00-d25e-11ea-80ab-85b08da921b2.png)

**To Reproduce**

1. Install Roam Chrome app
2. Reset Chrome to default settings
3. Click on Roam app
4. See bug

**System Information:**
 - Roam version: ?
 - Device: Desktop
 - OS: Windows
 - Browser Chrome 84.0.4147.105

**Comment by RobMcClusky** [comment]
Resolved. The Chrome App install worked perfectly on Monday, and it's been great for three days now. This issue is now solved.

**Comment by bezark** [comment]
Wait I've been having the same issue... I "install" the roam app on my mac with the chrome shortcut and it creates a desktop shortcut, but when the I I open the mac app it just opens a chrome tab instead. Any ideas on how to solve this?
