### ISSUE TITLE
Creating a new page using existing text failed

### ISSUE THREAD

**Issue by TheoKoster** [Roam-Research/issues#46]
Feature to create a page by highlighting existing text and clicking twice on the “[” keyboard fails. Since April 29th this action creates [[]selectedword] with the cursor between the inner square hooks.

To reproduce
See https://twitter.com/jarodise/status/1255350594434404352?s=20 for @jarodise video

System
OS: MacOSX 10.15.4 (latest & greatest)
Browser: Safari

**Comment by TheoKoster** [comment]
Feature to create a page by highlighting existing text and clicking twice on the “[” keyboard fails. Since April 29th this action creates [[]selectedword] with the cursor between the inner square hooks.

**To reproduce**
See https://twitter.com/jarodise/status/1255350594434404352?s=20 for @jarodise video

**System**
OS: MacOSX 10.15.4 (latest & greatest)
Browser: Safari

**Comment by mmower** [comment]
I'm hitting this one a lot in writing today.

**Comment by anshbansal** [comment]
This is happening with me also. Noticed this today.

**Comment by jetportal** [comment]
same! noticing since this AM

**Comment by chrisatherton71** [comment]
This is happening for me too, started the last day or so, MacOS.

**Comment by Serley** [comment]
Same here for the past 2 days. It doesn't seem related to accented characters for [[]Test]

**Comment by anshbansal** [comment]
This is not happening for me now. MacOS Catalina Brave Browser

**Comment by cori** [comment]
me too macOS Catalina Safari

**Comment by filipesilva** [comment]
Yeah I think a fix for this came out later yesterday. It should be fixed now if you refresh the page.
