### ISSUE TITLE
Import error: page objects require a title key

### ISSUE THREAD

**Issue by mcdonovan** [Roam-Research/issues#461]
**Describe the bug**

When I import a json file it reports the above error and does not import any files.

**To Reproduce**

1. Go to three dots in upper right corner
2. Click on 'Import files'
3. Click on 'choose files'
4. Select json file from local drive
5. Select 'open'
6. Click on 'Import [number] files'
7. See bug

<img width="554" alt="import error" src="https://user-images.githubusercontent.com/8955997/89119925-fcbcb600-d505-11ea-85e6-d6e778219f15.png">

**System Information:**
 - Roam version: 0.7.2-a2f6f4fd
 - Device: Macbook Pro
 - OS: MacOS Catalina 10.15.6
 - Browser Chrome (but using the "install roam research" feature)

**Comment by filipesilva** [comment]
@mcdonovan I think I know what's wrong, pushing a fix for it today. Sorry about the trouble!

**Comment by TristanH** [comment]
Wonderful, thanks @filipesilva !
