### ISSUE TITLE
Cursor moves to beginning of page ref while typing 

### ISSUE THREAD

**Issue by dgdulaney1** [Roam-Research/issues#463]
**Describe the bug**

When I quickly type [[ and begin typing a page name, my cursor jumps from its current position to the start of the page ref. 

![roam-cursor-bug](https://user-images.githubusercontent.com/46381940/89202809-8067b880-d581-11ea-8561-da9865be223e.gif)

**To Reproduce**

It's possible others with large databases are able to recreate this issue, but it's so simple that I would've expected to see it mentioned elsewhere if it was more prevalent. I'm not sure if others _are_ able to recreate this.

**System Information:**
 - Roam version: 0.7.2-a2f6f4fd
 - Device: Desktop computer
 - OS: Windows 10
 - Browser Vivaldi

**Additional context**

I have a large database and this bug becomes more common when I'm running several programs on my machine (e.g. during Zoom calls, this happens constantly.)

**Comment by spikedom** [comment]
See also https://github.com/Roam-Research/issues/issues/449

**Comment by dgdulaney1** [comment]
Thanks, @spikedom . Closing this issue.
