### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by wwingler** [Roam-Research/issues#466]
<img width="324" alt="typo" src="https://user-images.githubusercontent.com/69214145/89328578-98ac0600-d65b-11ea-884b-777acae69ae3.png">
**Describe the bug**
Was pasting a large block of text into Roam.  Got the attached error message.  "To" should be "Too".

**Comment by spikedom** [comment]
An even better message would say how big the failing paste was, and what the limit was that has been exceeded.

**Comment by wwingler** [comment]
That's true.  However, I think "To" should be spelled "Too" regardless of
the size of the paste and limit.  Sorry to be snarky, but you tickled my
funny bone.
