### ISSUE TITLE
Sub references aren't consistently inherited by a parent reference

### ISSUE THREAD

**Issue by bbozzay** [Roam-Research/issues#467]
**Describe the bug**

![2020-08-04 10 48 51](https://user-images.githubusercontent.com/17435217/89343975-5fc35f80-d662-11ea-841d-969b965f6a7c.gif)

**To Reproduce**

1. Create a list with sub items
2. Create a reference to the parent node of the list
3. Modify the referenced item by adding another bullet point
4. The referenced group should not show the new bullet point on the cloned version

**Comment by Bardia95** [comment]
Hi @bbozzay I don't understand what you're describing here. Could you be a bit more clear?

**Comment by bbozzay** [comment]
@Bardia95 I think this is working as intended, but it's confusing to the user. If I ctrl+drag a list by dragging the parent point, I can modify the sub points and those changes will be reflected across each reference. However, if I add a new sub-point, it is not reflected across each reference. I think block embeds are meant to be used in this case.
