### ISSUE TITLE
Pasting into a block adds the pasted text as a new subblock, rather than in the block

### ISSUE THREAD

**Issue by kylestratis** [Roam-Research/issues#469]
**Describe the bug**

When I paste text into an existing block (such as a URL), that text gets added as a subblock, although typical and expected behavior would be for the text to be pasted where the cursor is.

<img width="174" alt="image" src="https://user-images.githubusercontent.com/4088051/89460969-2f022980-d739-11ea-9095-5cb48c434fe2.png">
In this first image, the cursor is in the middle of the two words.

<img width="170" alt="image" src="https://user-images.githubusercontent.com/4088051/89461060-4fca7f00-d739-11ea-827a-1b2a33b8bf6e.png">

**To Reproduce**

1. Create a block
2. Put the cursor anywhere in that block
3. Paste text
4. Observe that the pasted text is in a subblock

*Note:* Occasionally to reproduce, you'll have to click away from the block then click back to it.

**System Information:**
 - Roam version: 0.7.2-85e079e2
 - Device: Macbook Pro
 - OS: MacOS 10.15.5
 - Browser: Firefox

**Comment by igor-kupczynski** [comment]
Noticed the same on both linux chrome and macos safari `0.7.2-85e079e2`. I think it got broken with the recent update.

**Comment by filipesilva** [comment]
I think this was a regression that @Bardia95 fixed a couple of hours ago, and should already be available live. You might need to close all tabs and reopen one to get the update faster if "check for updates" on the three dot menu says there's nothing (this only checks once a day on any single tab). At any rate, latest live is `0.7.2-c574ba90`, I tried on that version and could not reproduce anymore.

**Comment by kylestratis** [comment]
Thanks @filipesilva and @Bardia95 - I can no longer reproduce the bug either. Great work!
