### ISSUE TITLE
Attributes/Page Links are being created in LaTeX sections

### ISSUE THREAD

**Issue by ceejaypark** [Roam-Research/issues#471]
A double colon (::) generates attributes which create page links. This is happening inside of LaTeX sections which ends up creating unwanted links. 

**To Reproduce**

1. On any page, write LaTeX that contains double colons after a section of text.
e.g.
$$\vdash::b$$
This will create and link to a page called $$\vdash
2. Look at All Pages and you will find the pages created.

**System Information:**
 - Roam version: 0.7.2-c574ba90
 - Device: Laptop
 - OS: Windows
 - Browser: Firefox

**Additional context**

This doesn't seem like intended behavior. For example having double colons inside code blocks do not generate links in the same way.

**Comment by Bardia95** [comment]
Hi there, I wasn't able to reproduce this issue, are you still finding this to be a problem?

**Comment by ceejaypark** [comment]
> 
> 
> Hi there, I wasn't able to reproduce this issue, are you still finding this to be a problem?

Yes it's still happening

Here's the block
![roam1](https://user-images.githubusercontent.com/8573290/90838126-5a228500-e397-11ea-9910-7320edb1002f.png)

And here's the page created
![roam2](https://user-images.githubusercontent.com/8573290/90838152-71fa0900-e397-11ea-81fb-56f205638488.png)

**Comment by Bardia95** [comment]
Ok I was able to reproduce now, that's very strange, will look into it!

**Comment by Bardia95** [comment]
Ok, that's an issue with the parser it seems, will try and fix this!

**Comment by panterarocks49** [comment]
Deploying a fix for this today
