### ISSUE TITLE
Can't define links which have parenthesis

### ISSUE THREAD

**Issue by ozanozyegen** [Roam-Research/issues#472]
Can't define links if there are parenthesis in the link. Is there are workaround?

To replicate: Add the following to a block
`[paper](http://idosi.org/wasj/wasj(ITMIES)13/28.pdf)`

System Information:

Roam version: 0.7.2-c574ba90
Device: Laptop
OS: Windows
Browser: Chrome

**Comment by uasi** [comment]
As a workaround, you can use [percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) to escape parens in the URL: `[paper](http://idosi.org/wasj/wasj%28ITMIES%2913/28.pdf)`
