### ISSUE TITLE
Issues with embedded blocks appearing in the linked references

### ISSUE THREAD

**Issue by aasiaeet** [Roam-Research/issues#477]
I create a block B0 with the text: "Test block referencing".
![image](https://user-images.githubusercontent.com/17616890/89912405-83d1f400-dbc0-11ea-982b-ad0d81ac175e.png)

I reference it in another block B1. 
![image](https://user-images.githubusercontent.com/17616890/89912234-52592880-dbc0-11ea-881b-db0f8158312c.png)

I embed B0 in another block, B2. 
![image](https://user-images.githubusercontent.com/17616890/89912314-6ac94300-dbc0-11ea-929a-77e34458393a.png)

I zoom in B0 and check the linked references:
![image](https://user-images.githubusercontent.com/17616890/89912452-93513d00-dbc0-11ea-8b7c-2d129730cb7b.png)

As you see, the embedded block appears as regular red text (without any formatting, for example, even if it is a TODO it is not appearing like so)
![image](https://user-images.githubusercontent.com/17616890/89912642-c72c6280-dbc0-11ea-92bd-8a6960bfd457.png)

Checking the source: 
![image](https://user-images.githubusercontent.com/17616890/89912720-e1664080-dbc0-11ea-94a0-b93a035f4226.png)

**Comment by Bardia95** [comment]
This is not a bug this is a feature to prevent infinite renders. Sorry if that wasn't clear.
