### ISSUE TITLE
After update→ Linked/Unlinked References→ when top-level bullet has children, the "•••" covers the bullet to reveal blocks underneath

### ISSUE THREAD

**Issue by beauhaan** [Roam-Research/issues#478]
**After update→ Linked/Unlinked References→ when top-level bullet has children, the "•••" covers the bullet to reveal blocks underneath**

→ When on a page with Linked Refernces→ if a block has children underneath the block the "•••" covers the bullet to reveal the blocks underneath.

<img width="303" alt="Screen Shot 2020-08-11 at 11 06 42 PM" src="https://user-images.githubusercontent.com/69569969/89980736-5704f780-dc27-11ea-9982-16e811215e2e.png">

If applicable, add screenshots to help explain your problem. You can paste them in here and they will be uploaded automatically.

If you have a video of you experiencing the bug, that is also super helpful!

**To Reproduce**

4. See bug

**System Information:**
 - Roam version: 0.7.2-1112e682
 - Device: MacBook 
 - OS: 10.15.6 Catalina
 - Browser: Safari

**Additional context**

**Comment by ivanz** [comment]
Same problem for Block Embeds - it's really broken my flow as I can't expand/collapse anything embedded at the moment:

![image](https://user-images.githubusercontent.com/79742/90050221-ce8d6200-dccd-11ea-9ff8-78eecf1136c9.png)

**Comment by beauhaan** [comment]
Command+UP, and Command+DOWN is a workaround for now, and if you click closer to the right of the "..." does still open the children blocks.

**Comment by pmbauer** [comment]
similar issue for chromium browsers where the '...' menu isn't visible in the sidebar next to nodes with children. It's likely a bug in the default CSS theme as it doesn't manifest in all themes.

**Comment by kylestratis** [comment]
Experiencing in Chromium browsers (Vivaldi) as well, with an additional screenshot - I'm using the Cosmonaut theme but it also exists in the default CSS:
![image](https://user-images.githubusercontent.com/4088051/90131072-82780700-dd39-11ea-9793-80a565dcd932.png)

**Comment by Bardia95** [comment]
This was rolled back in a recent update, so I'm closing this issue!
