### ISSUE TITLE
Toggle is broken when indented.

### ISSUE THREAD

**Issue by jesserayn** [Roam-Research/issues#480]
**Describe the bug**

If applicable, add screenshots to help explain your problem. You can paste them in here and they will be uploaded automatically.
![image](https://user-images.githubusercontent.com/57831376/90072474-4f3b6680-dcac-11ea-9adb-f9af15acbbcd.png)

If you have a video of you experiencing the bug, that is also super helpful!

**To Reproduce**

4. See bug

**System Information:**
 - Roam version: [e.g 0.5.0-43911ff0, find it at the end of the help button pop up]
 - Device: [e.g. iPhone6, desktop computer]
 - OS: [e.g. iOS8.1, Windows, ]
 - Browser [e.g. Chrome, Safari, FireFox, Brave]

**Additional context**

**Comment by Bardia95** [comment]
Hey this was fixed in a recent rollback, sorry about that!
