### ISSUE TITLE
#page_name leads to floating auto-complete box that does not disappear

### ISSUE THREAD

**Issue by royYYZSFO** [Roam-Research/issues#482]
**Describe the bug**

https://share.getcloudapp.com/4gu99djZ

**To Reproduce**

See video.

**System Information:**
 - Roam version: [e.g 0.5.0-43911ff0, find it at the end of the help button pop up]
 - Device: Macbook Pro
 - OS: 10.15.6
 - Browser Chrome (latest version)

**Additional context**

**Comment by filipesilva** [comment]
Heya, we just pushed a fix for this. Should be available by doing "check for updates", or when you close all roam tabs and open one again.

Sorry for the trouble!
