### ISSUE TITLE
Latest update breaks editing linked references

### ISSUE THREAD

**Issue by kylestratis** [Roam-Research/issues#484]
**Describe the bug**

Before today's update, I was able to edit linked references (e.g. on my daily notes) directly on the page. This is no longer possible as of the August 14th update.

**To Reproduce**

1. Open any page (daily note or otherwise) with linked references.
2. Attempt to edit the linked reference.
3. Nothing happens

**System Information:**
 - Roam version: 0.7.2-52af6683
 - Device: Macbook
 - OS: MacOS Catalina
 - Browser Vivaldi (Chromium)

**Additional context**

This only began with the latest update.

**Comment by pmbauer** [comment]
can confirm, I see the same

**Comment by pmbauer** [comment]
also, this isn't just for the daily notes; back-references are no longer editable

**Comment by pmbauer** [comment]
linked references in the sidebar are also un-editable
Another weird artifact is heading formatting is lost; clicking in the linked reference causes the heading formatting to take effect and makes the UI jump.

**Comment by cyrulnik** [comment]
I see the same problem after the latest update across different browsers. Linked references are not editable. It is possible to check and uncheck "todo" items --and also possible to right click and open the reference in the sidebar, where it is editable. But cannot edit inline.

**Comment by panterarocks49** [comment]
Deploying a fix in a minute, will close when it's deployed

**Comment by pmbauer** [comment]
Thanks!!

**Comment by kylestratis** [comment]
Thanks @panterarocks49! Looks good to me!

**Comment by danstern213** [comment]
I'm still seeing this broken on my end, same behavior that was in the initial issue (currently using Chrome)!
