### ISSUE TITLE
impossible to horizontal scroll on tables

### ISSUE THREAD

**Issue by pmbauer** [Roam-Research/issues#485]
**Describe the bug**

If a table's contents are wider than the roam article width, a horizontal scroll appears in the table area.
But, it is impossible to horizontally scroll to view the rest of the table contents.

**To Reproduce**

![Screen-Recording-2020-08-15-at-1](https://user-images.githubusercontent.com/453580/90315585-9c0c8080-deea-11ea-8005-f8b6e16fd2e5.gif)

1. Create a table with 4-5 columns of content, enough to force a horizontal scroll
2. Try clicking on the scroller

**System Information:**
 - Roam version: 0.7.2-fd6134ee
 - Device: desktop
 - OS: MacOS 10.15
 - Browser: Brave

**Comment by ssalka** [comment]
The workaround here is to scroll while holding the shift key, rather than trying to drag the scroll bar

**Comment by Bardia95** [comment]
Fixed it!
