### ISSUE TITLE
CTRL-C CTRL-B does two things

### ISSUE THREAD

**Issue by mtnygard** [Roam-Research/issues#493]
**Describe the bug**

In the help popup, Ctrl-C Ctrl-B is described as cycling brackets. It does this, but if any item is in "edit mode", the Ctrl-B *also* bolds the current selection.

**To Reproduce**

1. Go to Daily Notes
2. Enter any item with a bracketed link
3. Click in whitespace to clear the cursor.
4. Type Ctrl-C Ctrl-B. Observe that the `[[` and `]]` appear.
5. Click onto any line
6. Type Ctrl-C Ctrl-B. Observe that the `[[` and `]]` disappear
7. Also note the `****` that appeared around your cursor.

**System Information:**
 - Roam version: 0.7.2-6fccb616
 - Device: desktop
 - OS: Windows 10
 - Browser: Firefox 79.0

**Additional context**

Nothing else.

**Comment by Bardia95** [comment]
Hi please use Ctrl-C Ctrl-B while not focused inside a block!
