### ISSUE TITLE
Queries no longer return any results as of 0.7.3-0f43b379

### ISSUE THREAD

**Issue by spikedom** [Roam-Research/issues#494]
**Describe the bug**

Queries return no results.

**To Reproduce**

{{query: {and: [[TODO]]}}}

**System Information:**
 - Roam version: 0.7.3-0f43b379
 - Device: PC
 - OS: Windows
 - Browser: Chrome

**Comment by csarmendariz** [comment]
> {{query: {and: [[TODO]]}}}

In my case a simple TODO query like the one here seems to be the only one that works.
However any other query doesn't:

![Selection_145](https://user-images.githubusercontent.com/40965727/90630210-8663c780-e218-11ea-8625-14e17b3667be.png)

**Comment by matiassingers** [comment]
This has been fixed now, try updating.

**Comment by csarmendariz** [comment]
Yes, working for me after updating!
