### ISSUE TITLE
Typeahead tag completion often creates a new tag/page without user intent

### ISSUE THREAD

**Issue by jjthrash** [Roam-Research/issues#498]
**Describe the bug**

Occasionally when I am using typeahead to look for a tag, Roam creates a new page at the top as a choice using the partial text I've typed. This steals cursor focus and often leads me to select the wrong item.

**To Reproduce**

1. View a page with a lot of content
2. Start adding a new node/block (type enter at the end of another block)
3. Type some content.
4. Start typing a tag, using text in the *middle* of the tag. E.g. if I'm looking for `C: Development` type `#deve`
5. If there are a bunch of pages that match, often it will create a new page as the top item in the list.
6. The page is there in subsequent typeahead sessions until I reload the page. Like this: [screenshot](https://www.dropbox.com/s/ycbogp1agxqkaed/Screen%20Shot%202020-08-20%20at%204.51.50%20PM.png?dl=0)

**System Information:**
 - Roam version: 0.7.3-e272efd5
 - Device: Macbook Pro
 - OS: MacOS 10.15.5
 - Browser: Firefox (https://www.whatsmybrowser.org/b/5WP95)

**Additional context**

This may be performance related. The below analysis is not scientific and may suffer from confirmation bias. It's hard one to reproduce consistently. :(
- It's less likely to happen if I've only recently opened Firefox
- I have 27K blocks (things with `uid` values in the JSON export) in my map
- I have 5K pages (things at the top level in the JSON export) in my map
- It often happens if I edit the text I've typed.. e.g. in the above example type `#devp`, then backspace, then `e`

**Comment by freddiesheehan** [comment]
I am having the same issue. I have found that it does not happen if I put a # in front of the double brackets. It has happened to me on a macbook, and two windows pcs, on safari, firefox, and chrome. 

For me, it doesn't need to be in the middle of the brackets. anything i write in [[]], if i pause, then a new page is created.

Another oddity is that if you follow this process, open [[]], type anything, wait for a second, then backspace the whole thing away a new page is created. But if the first thing you click after doing this little test is "All Pages", the accidentally created page appears for a second but then disappears and no longer exists.

System Information
MacBook Air MacOS 10.15.6 and Windows 10
Browsers tried: Safari, Chrome, Firefox

**Comment by panterarocks49** [comment]
I can't reproduce this, but might be related to #492 . Could you try this url and see if it's fixed for you there?
https://relemma-git-fix-492.roamresearch.now.sh

**Comment by jjthrash** [comment]
@panterarocks49 Will do. I'll use this URL today, though it may take some time to reproduce.

Any actions to take if/when I reproduce

**Comment by panterarocks49** [comment]
Reply here if you do/don't have any issues, I'll probably deploy this before tomorrow anyway since it seems to fix #492

**Comment by jjthrash** [comment]
@panterarocks49 It has worked well for me all day today.

**Comment by panterarocks49** [comment]
Awesome, I'll get this deployed later today

**Comment by freddiesheehan** [comment]
This URL works for me as well. Haven't tried it for very long but will give
it more time and update if the problem comes back.

Thank you,
Freddie

**Comment by panterarocks49** [comment]
Awesome, deploying the fix to production now.
