### ISSUE TITLE
Highlight + [[ + 'return' too fast = issue

### ISSUE THREAD

**Issue by jegirard** [Roam-Research/issues#502]
**Describe the bug**

If I highlight a word or phrase, type [[ to turn it into a page AND hit return before Roam catches what’s going on and displays the “search for page” box, things glitch - the highlight phrase is replaced by a hard return, and then when I undo, block gets gets partially… Odd behavior. Fix is to wait a beat after hitting [[ for the search box to show up, but definitely a bug

https://www.loom.com/share/0d522eedb9134ef3869075345b326c64

**To Reproduce**

1. paste in a block of text
2. highlight a word or phrase in block
3. type [[ + 'return' very quickly
4. text is replaced by a hard retrurn
5. cmd-z to undo replace - weirdness happens

**System Information:**
 - Roam version: 0.7.3-3749cce3
 - Device: iMac
 - OS: Catalina (10.15.6 (19G73))
 - Browser Chrome

**Additional context**

**Comment by panterarocks49** [comment]
I've got a fix in the works for this, will close when it's deployed

**Comment by jegirard** [comment]
Great to hear! Thank you..
