### ISSUE TITLE
Can't edit linked references

### ISSUE THREAD

**Issue by danstern213** [Roam-Research/issues#503]
**Describe the bug**

I'm not able to edit any linked reference from a page.

**To Reproduce**

1. Go to any page
2. View linked references
3. Try to edit linked reference directly from the page

Also:
1. Open any page in the sidebar
2. Click Mentions
3. Filter for a specific linked page
4. Try to edit linked reference directly from page

 - Roam version: 0.7.2-52af6683
 - Device: Macbook
 - OS: Mojave 10.14.6
 - Browser: Google Chrome

**Comment by panterarocks49** [comment]
I think this is fixed in 0.7.3 onward could you try upgrading?

**Comment by danstern213** [comment]
Fixed!  I must not have been on the newest version.  Thanks so much for the
help and fast reply
