### ISSUE TITLE
Make order of words within inline [[]] search not matter

### ISSUE THREAD

**Issue by classicrob** [Roam-Research/issues#504]
**Describe the problem**

See this example here - it feels very wrong that skipping a few words in adding in the word "capable" pulls up empty results. There have been countless times when pages don't show up while I'm looking for them with inline double brackets, leading to me feeling frustrated. (()) does allow me to type words in any order.
![image](https://user-images.githubusercontent.com/46608303/91179330-9873b900-e6a3-11ea-8e32-1846f490c6a4.png)
![image](https://user-images.githubusercontent.com/46608303/91179345-9b6ea980-e6a3-11ea-9106-71e887496511.png)

**Feature implementation**

I just want it to make it so I can type words in any order **like I can with block reference (()) search.** This would be a **huge** quality of life improvement.

**Additional context**

Alternatively, this would solve the same problem. [Keyboard shortcut to copy block or page reference from the the search bar and paste into where I was previously typing](https://github.com/Roam-Research/issues/issues/505)

**Comment by filipesilva** [comment]
Heya, @Bardia95 submitted a fix for this yesterday actually. Should be live now if you check for updates, or close all tabs and reopen one.

**Comment by classicrob** [comment]
Fantastic, thank you so much! This is a major improvement to the UX.
