### ISSUE TITLE
"Return" and up/down keys "disabled" after entering tag

### ISSUE THREAD

**Issue by jegirard** [Roam-Research/issues#508]
**Describe the bug**

Strange one. If I enter text, and at the end of the text type a tag in the form #thisisatag AND HIT "return" when I'm done typing the tag, the return key becomes "disabled" - hitting it again doesn't create a new line, no matter how many times I hit it. Also, the up and down arrow no longer function.

The only way to correct it is to click on another line in the app then back on the bullet in question.. That seems to "reset" normal behavior.

Guessing its a tag-picker dialog bug of some kind.

Note: this does NOT happen if I press SPACE after entering the tag - only if I hit return

**To Reproduce**

See above. Here's a video https://www.loom.com/share/e853e7115bb34cb89eb0117b19d5d43e

**System Information:**
 - Roam version: 0.7.3-9c47dab1
 - Device: iMac
 - OS: Catalina
 - Browser Chrome

**Additional context**

**Comment by skrifblokk** [comment]
Seconding this issue. Same system info except device.

**Comment by GitMurf** [comment]
Thirding this issue. Very very annoying! Didn't know how much I ended blocks with hashtag references until this bug appeared ;)

**Comment by skrifblokk** [comment]
This appears to be fixed with today's update.
