### ISSUE TITLE
Bold Text Functionality is Broken in outline component

### ISSUE THREAD

**Issue by systemizer** [Roam-Research/issues#509]
**Describe the bug**
Bold text does not work when pressing Ctrl-B.

javascript error occurs in console when attempting to bold text

If applicable, add screenshots to help explain your problem. You can paste them in here and they will be uploaded automatically.
![Capture](https://user-images.githubusercontent.com/625343/91749003-bd6d9d80-eb75-11ea-9735-ba05471e83e5.PNG)

If you have a video of you experiencing the bug, that is also super helpful!

**To Reproduce**

1. Go to any page
2. Highlight Text
3. Press Ctrl-B

**System Information:**
 - Roam version: 0.7.3-5832b75e
 - Device: desktop computer
 - OS: Windows
 - Browser: Chrome

**Additional context**

Started occurring in the last 24 hours

**Comment by fav-rock** [comment]
Also, wrapping it with asterisks (*bold text*) doesn't work for me.

**Comment by jsiddharth24** [comment]
Wrapping with **double asterisks** works but same the shortcut Ctrl+B does not work. Happening since today (31st Aug) morning. 
![image](https://user-images.githubusercontent.com/25843960/91768168-259f9c00-ebd5-11ea-8863-db7ef2491650.png)

**Comment by systemizer** [comment]
Seems to be fixed for me. @jsiddharth24 can you verify on your end? If that's the case, I'll close the issue.

**Comment by jsiddharth24** [comment]
Hey @systemizer - still not fixed at my end.

**Comment by jsiddharth24** [comment]
Works now! Thank you so much.
