### ISSUE TITLE
Square brackets not showing around Page References

### ISSUE THREAD

**Issue by erinjeannew** [Roam-Research/issues#520]
**Describe the bug**

I was writing in Roam when all of the square brackets disappeared from around page references on my graph. You now can't distinguish between a Page Reference and a normal hyperlink. Examples:

![Screenshot 2020-09-13 144042](https://user-images.githubusercontent.com/71219326/93019471-1f46f200-f5cf-11ea-8547-08bfd44ceaeb.png)
![Screenshot 2020-09-13 144251](https://user-images.githubusercontent.com/71219326/93019531-7e0c6b80-f5cf-11ea-9603-6deb408269b5.png)
![Screenshot 2020-09-13 144316](https://user-images.githubusercontent.com/71219326/93019536-82d11f80-f5cf-11ea-82a4-f232dcdc4a19.png)

However, when I go into e.g. the Roam help graph, I can see the square brackets around page references (and hyperlinks) as normal, so seems to only be affecting my graph. Example:

![Screenshot 2020-09-13 143829](https://user-images.githubusercontent.com/71219326/93019420-d131ee80-f5ce-11ea-8e62-af3d059537f1.png)

**To Reproduce**
Not sure how to reproduce! Just a state of being at the moment.

**System Information:**
 - Roam version: 0.7.3-1a824a67
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome Version 85.0.4183.102

**Comment by 0dB** [comment]
Maybe you accidentally activated this feature here:

Ctrl-c Ctrl-b Toggle brackets

**Comment by erinjeannew** [comment]
Ah brilliant, thanks so much @0dB! That did the trick.
