### ISSUE TITLE
Local graphs not loading

### ISSUE THREAD

**Issue by alxjsn** [Roam-Research/issues#523]
**Describe the bug**

Trying to open any local graph results in a loading screen that never ends. The local graph never gets opened.

**To Reproduce**

1. Restart browser and go to the Roam Research application. 
2. Create a new local graph or try to open a previously create local graph.

**System Information:**
 - Roam version: 0.7.3-45c41a7d
 - Device: Laptop
 - OS: Mac/Linux
 - Browser Chrome/Firefox

**Comment by djgreen123** [comment]
I also have this problem.  I can not open local graphs or create new ones.  Remote graphs work as expected.

Chrome Version 85.0.4183.102 (Official Build) (64-bit)
macOS Catalina 10.15.6

Not a good start to my Believer package but I still believe! :)

**Comment by Bardia95** [comment]
Fixed in most recent update by @filipesilva, please check for update :)

**Comment by djgreen123** [comment]
All good. Thanks.

**Comment by alxjsn** [comment]
Working here as well now. Thank you!
