### ISSUE TITLE
Input caret moves 2 chars to the right when typing the number ‘3’.

### ISSUE THREAD

**Issue by keikhcheung** [Roam-Research/issues#525]
**Describe the bug**

The input caret / I-beam always jumps 2 characters to the right when you type the number `3`.

**To Reproduce**

1. Go to any position in a text string (before the last character).
2. Type `3`.
3. See bug.

**System Information:**
 - Roam version: 0.7.3-fb902a7b
 - Device: MacBook Pro
 - OS: macOS 10.14.6
 - Browser: Chrome, Firefox

**Comment by Bardia95** [comment]
Hey there I wasn't able to reproduce this issue, can you please provide a screen share with the issue in action?

**Comment by keikhcheung** [comment]
I figured out it's likely to be a bug conflict with a plug-in. Thanks for the follow-up.
