### ISSUE TITLE
Cmd + Shift + \ to close the sidebar forces a full refresh

### ISSUE THREAD

**Issue by kylestratis** [Roam-Research/issues#537]
**Describe the bug**

When closing the sidebar with the new cmd + shift + \ shortcut, instead of closing the sidebar roam is force-refreshed.

**To Reproduce**

1. Open sidebar by any method
2. Close with cmd + shift + \
3. Observe a full refresh
  3a. You may also observe a short flash of an error message before the refresh

**System Information:**
 - Roam version: 0.7.4-b62d4105
 - Device: Macbook Pro
 - OS: MacOS Catalina 10.15.6
 - Browser Chrome and Firefox

**Additional context**
https://www.loom.com/share/ae80a0dca49148239a55b13aaf0d7866

**Comment by GitMurf** [comment]
Yep, same issue on Windows with chrome or firefox.

**Comment by Bardia95** [comment]
This has been fixed, sorry about that!
