### ISSUE TITLE
Hyperlink shortcut with selected text inserts wrong markdown format

### ISSUE THREAD

**Issue by keikhcheung** [Roam-Research/issues#57]
**Describe the bug**

Problem when using `Cmd + K` to hyperlink text with selected text:

- When the block does not contain any hyperlink, the shortcut `Cmd + K` works fine. It puts the selected texts in brackets and let you paste directly your URL in parentheses, i.e. `[selected text](I)`.

- When the block already contain one or more hyperlinks, using `Cmd + K` puts the selected text in parentheses and put the input caret in brackets (which does not make sense), i.e. `[I](selected text)`.

**To Reproduce**

1. Select some text.
2. `Cmd + K` and paste the URL.
3. Select some other text _within the same block_.
4. `Cmd + K`.

**System Information:**
 - Device: MacBook Pro (Retina, 15-inch, Mid 2015)
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome, Firefox, Safari

**Comment by panterarocks49** [comment]
Same as https://github.com/Roam-Research/issues/issues/58
