### ISSUE TITLE
JSON import fails if page title includes a [[reference]] to a page that already exists in your graph

### ISSUE THREAD

**Issue by TristanH** [Roam-Research/issues#579]
**Describe the bug**
JSON import fails if page title includes a [[reference]] to a page that already exists in your graph. This can be especially problematic for backups, as it's conceivable this bug would prevent you from importing a previously exported version of your graph.

**To Reproduce**

1. Make sure you have a page titled `inbox` in your roam graph
2. Import a file to roam with this content:

> [{"title": "[[inbox]]/this won't import", "children": [{"string":  "hello"}]}]

3. The import will fail with error message ", even though that page title is valid and the page does not exist in roam.

**Comment by TristanH** [comment]
Noticed this also happens with content inside of an imported file.

If you have a block with the text `[[[[inbox]]]]`in your json file and the page `inbox` already exists in your Roam database, the import will also fail.

**Comment by Bardia95** [comment]
Was able to reproduce the first issue but not "If you have a block with the text [[[[inbox]]]]in your json file and the page inbox already exists in your Roam database, the import will also fail."

Could you record a screen recording of it failing?

**Comment by TristanH** [comment]
@Bardia95 thanks for the quick turnaround!

Here's the screenrecording:

https://www.loom.com/share/53068cabca1d4e46bd5a1cab71f2e34a

And here's the file I used:

> [{"title": "this won't import either", "children": [{"string": "hello [[[[inbox]] inside other ref]]"}]}]

**Comment by filipesilva** [comment]
@TristanH I tried following these steps but I can't get the error message. Do you still see this happening?

**Comment by TristanH** [comment]
Looks like you guys fixed it at some point since Oct! :) Happy to close.
