### ISSUE TITLE
Ctrl-k doesn't work properly after the first time in a single block

### ISSUE THREAD

**Issue by arozbiz** [Roam-Research/issues#58]
**Describe the bug**

After the first time I use ctrl-k in a block to create a markdown link (with a URL), it doesn't select the correct text to put in the []. See video.
![bug](https://user-images.githubusercontent.com/4499657/80745671-43091000-8ae6-11ea-9d59-66fc1a1aa200.gif)

**To Reproduce**

1. In a block, type some text.
2. Select the text, press ctrl-k and enter a URL
3. In the same block, type some more text.
4. Select the new text, press ctrl-k.

**System Information:**
 - Device: Desktop
 - OS: Windows
 - Browser Chrome

**Comment by MarcCoet** [comment]
Think this one can be closed.
Can you confirm @arozbiz ?

**Comment by arozbiz** [comment]
Still having the same problem, even after reloading Roam.

**Comment by panterarocks49** [comment]
Deploying a fix for this today, should be up in about 20 minutes

**Comment by arozbiz** [comment]
Nice! It works. Thank you.
