### ISSUE TITLE
Shortcut command conflict with Safari in MacOS

### ISSUE THREAD

**Issue by m3kwong** [Roam-Research/issues#581]
**Describe the bug**
A few short cuts such as cmd-shift-\(right side bar) and cmd-shift-h(highlight) is already used by Safari.  They don't work or does the 2 conflicting commands at once. 

There are probably more, but I haven't tried others yet.

**To Reproduce**

1.In editing mode, try cmd-shift-\(right side bar) or cmd-shift-h(highlight)

**System Information:**
 - Roam version: 0.7.4-72785d54
- MacOS 10.15.7
- Safari Version 14.0 (15610.1.28.1.9, 15610)

**Additional context**

**Comment by pmbauer** [comment]
Note that `cmd-shift-\` is now replaced by `cmd-/` as of `0.8.1-561aab9a` and partially fixes this issue.

**Comment by m3kwong** [comment]
It works good. Amazing work
