### ISSUE TITLE
Cannot rename pages

### ISSUE THREAD

**Issue by andrew-j-roberts** [Roam-Research/issues#587]
**Describe the bug**

I currently can't rename pages. Trying to backspace in a page title does nothing. I've opened in incognito and have emptied my cache.

**To Reproduce**

1. Go to any page
2. Attempt to rename title of page

**System Information:**
 - Roam version: 0.7.4-e229f208
 - Device: computer
 - OS: Mac latest
 - Browser: Chrome

**Additional context**

It's a private roam graph.

---

Fixed for me when I manually updated to 0.7.4-06236d67 on Macbook Pro, ty tylerwince for pointing out

**Comment by TheMuonNeutrino** [comment]
I have the same issue. However, for me it is device / OS specific.

It occurs on my laptop running Windows 10 (Chrome, Desktop app and Firefox).
It does not occur on my phone (Android).
It does not occur on my other laptop (Linux).

**Comment by tylerwince** [comment]
Also having this issue: 

Roam version: 0.7.4-e229f208
Device: Macbook Pro
OS: macOS 10.15.7
Browser: Chrome

**Comment by samhuleatt** [comment]
Same, I cannot edit/rename pages right now

**Comment by tylerwince** [comment]
@samhuleatt have you updated your Roam? What version are you on? (Find it by clicking the `?` in the bottom right and scrolling all the way to the bottom)

**Comment by samhuleatt** [comment]
You Sir, are a genius. Thank you. Didn't realize a manual update was
required.
