### ISSUE TITLE
Accented characters messed up all over DB

### ISSUE THREAD

**Issue by MrPiotrS** [Roam-Research/issues#59]
Recent change to Roam messed up my entire DB. I now have both `ś` (you can delete it with one backspace) and `ś` (you need to press backspace twice to remove it, first press changes it to `s`). You can copy both and paste them to some editable textarea to see that these are different letters even though they look the same. Same goes for other accented chars.
Now I can't connect text to older notes, because when I type something between [[]] that I already have in DB it changes it automatically to this new version and creates new page. I also can't search older notes and within their content. Unlinked References are also broken. Everything I typed recently is in this new version, everything I typed before is in older, different version, which means everything is broken.

**To Reproduce**

Type anything in letters from different language or copy and paste `ĄĘÓŚĆŻŹŃąęóśćżźń` into your page and press backspace anywhere within it.

**System Information:**
 - Device: laptop
 - OS: Mac 10.13
 - Browser: Chrome, Vivaldi, Firefox

**Additional context**

Exported content, in JSON and in markdown, is also broken.

No problem with deleting letters on Android (multiple browsers), but because it updates the letters there too, I can't search/link my older notes title/content.

**Comment by slaapme** [comment]
Same problem here !

**Comment by wilkerlucio** [comment]
Hello, a fix to this issue just got deployed, if you still see a problem to link any page, try opening the page, editing the title to anything else, and edit back to the original, after that the links should work normally.
