### ISSUE TITLE
Block deletion results in deletion of the parent block

### ISSUE THREAD

**Issue by kylestratis** [Roam-Research/issues#590]
**Describe the bug**

This was discovered by users losing data via Readwise's sync and Tristan at Readwise for debugging. Deleting a child block used to delete that block specifically, but as of the ~25th now deletes the parent block. This caused the Readwise sync (which deleted a single block previously) to delete daily pages as it needs to delete a block as part of its regular cleanup.

https://slack-files.com/TNEAEL9QW-F01DZMV6SG1-933183d846

**To Reproduce**

1. Create a page, call it "parent"
2. Create a block under it. You can even create a grandchild block
3. Focus on either block
4. Delete the block via the top menu, and the modal will prompt to delete the entire page. 

**System Information:**
 - Roam version: 0.7.4-06236d67
 - Device: Macbook Pro (my reproduction)
 - OS: MacOS 10.15.7
 - Browser Firefox

**Additional context**
A number of users were affected by the data loss that this has caused.

**Comment by Bardia95** [comment]
This is not a bug, and the expected behaviour. Before, the delete function was supposed to be for the page, but was incidentally working to delete the block as per Readwise's hack to remove the standard import statements :)
