### ISSUE TITLE
Scrolling is currently missing from iPad roam. 

### ISSUE THREAD

**Issue by domo206** [Roam-Research/issues#591]
You currently can not scroll at all on iPad. Tried using touchpad, fingers, arrow keys, etc. Only the sidebar has scrolling functionality. It’s completely vanished for anywhere else. 

Have tired different web browsers and saving and using roam as a app on home screen. Still no scrolling. 

Using iPad 10.2 with iPadOS 14.1

To reproduce just login on iPad and try to navigate your database. You can’t.

**Comment by chinarut** [comment]
I had this issue this morning as well. do a “check for update” and apply the update and everything should work fine.  I’m on iPadOS 14.1 as well.
