### ISSUE TITLE
Pin in the right sidebar stopped working since the new sidebar release

### ISSUE THREAD

**Issue by thesved** [Roam-Research/issues#604]
**Describe the bug**
Pinning items in the right sidebar doesn't keep them at the top.

**To Reproduce**

1. Open a page in sidebar
2. Pin it
3. Open another page in the sidebar
4. The pinned page isn't kept at the top

**System Information:**
 - Roam version: 0.7.5-41613cc4
 - Device: desktop
 - OS: mac
 - Browser: Chrome (86.0), Safari (14.0)

**Comment by anvimea** [comment]
My sidebar pins still show on my iOS devices, but don't show at all on Chrome. Any new pins made in Chrome fail to persist.

**Comment by thesved** [comment]
If I close (X) a pinned sidebar element, it keeps on reappearing when I open the sidebar again 😢

**Comment by Bardia95** [comment]
The pinned page was never meant to stay at the top
