### ISSUE TITLE
CTRL-ALT-N and CTRL-ALT-P to go to next/previous daily note only work on daily pages, not the scrolling daily note page

### ISSUE THREAD

**Issue by surrjon** [Roam-Research/issues#615]
These shortcuts allow movement to next/previous daily notes page - somewhat.
When you're on the daily page - e.g. you navigate to [[November 13th, 2020]]  - then CTRL-ALT-P takes me to [[November 12th, 2020]]
But, if I'm on the scrolling Daily Notes page, and it's showing today's date (November 13th) - my note is longer than one screen, so I'd love to hit CTRL-ALT-P to jump to November 12th.  And I can't.
These shortcuts only appear to currently work when you're on the daily page itself for the specific date, and not on the main Daily Notes page.  This greatly limits usefulness and is confusing - please help!

Not just experienced by me (@surrjon) but by several others on this thread: https://twitter.com/calhistorian/status/1326170090706853889?s=21

**System Information:**
 - Roam version: [0.7.5-1a045ae5]
 - Device: [MacBook Pro 2018]
 - OS: [Big Sur but also yesterday on the prior OS]
 - Browser [Chrome]

**Comment by Bardia95** [comment]
This is not a bug, we created the feature to work from the daily note page itself. You're asking for a new feature to have it work from the scrolling daily notes page :)
