### ISSUE TITLE
Last edit hover popup does not disappear and blocks ability to drag and drop blocks under it 

### ISSUE THREAD

**Issue by tombarys** [Roam-Research/issues#634]
**Describe the bug**

I struggle with the new “hover over icon” feature when trying to drag & drop a block. 

The popup with info shows up but does not disappear when trying to move the block around, which makes it very cumbersome. 

Result: I am always dropping the dragged block at the wrong place (as it is an indented sub-block of the one above). 

What am I doing wrong? Thanks!

**To Reproduce**

1. Go to any page with more blocks and choose some of them at the bottom 
2. Hover with the mouse pointer over the bottom block bullet point until the Edit popup appears
3. Click and drag the block (bullet) above as you want to move it up just one or two blocks/rows (on the 1st level of the page)
4. You can see that the Edit popup does not disappear and until the mouse is under the popup, it does not show the dragging "line."
5. Try to drop the block where you intended up 1-2 blocks above – it is not possible 

**System Information:**
 - Roam version: [0.7.5-227ec105]
 - Device: [iMac 27", 2019"]
 - OS: [MacOS Big Sur]
 - Browser [Safari]

**Additional context**

Add any other context about the problem [here.](url)
![cleanshot_2020-12-04_at_10 42 56](https://user-images.githubusercontent.com/5729352/101150995-5272ad80-3621-11eb-8312-a91e57b4fb30.gif)

**Comment by eiffair** [comment]
You're not the only one, same problem here with a similar configuration. Moving blocks just above is almost impossible to do accurately.

**Comment by tombarys** [comment]
I had to move from Safari because of that bug. I created a standalone Roam app with Coherence X, which runs on Chrome but does not open another Chrome instance (as other apps of this kind do). It works pretty well. Little advice: if you use Mac with M1 chip, Coherence X-created app does not work. You have to create your app on Intel and move the Roam app to M1 Mac. :)

**Comment by Bardia95** [comment]
This is solved, if you drag from just underneath the bullet the hover over does not appear
