### ISSUE TITLE
Bad bullet placement on Ubuntu/Firefox

### ISSUE THREAD

**Issue by teodorlu** [Roam-Research/issues#637]
**Describe the bug**

Bullets are placed too far down since about December 2nd. Before that, no complaint (regression). Any big CSS changes around that time?

This is what it looks like:

![image](https://user-images.githubusercontent.com/5285452/101331881-dcff1b00-3874-11eb-89c2-72f58959212f.png)

**To Reproduce**

View any page.

**System Information:**
 - Roam version: 0.7.5-e6ca640e
 - Device: Desktop / Thinkpad T490s
 - OS: Ubuntu 20.04
 - Browser Firefox 83.0 (64-bit)

**Additional context**

Reported on the Roam Slack around December 2nd.

![image](https://user-images.githubusercontent.com/5285452/101331810-c5279700-3874-11eb-957a-e994859543ac.png)

https://roamresearch.slack.com/archives/CN2L1UUHY/p1606917217223200

**Comment by Bardia95** [comment]
fixed

**Comment by teodorlu** [comment]
![image](https://user-images.githubusercontent.com/5285452/104161713-982a4f00-53f3-11eb-839b-b646063069db.png)

@Bardia95 care to take a look?

I'm not re-opening; this smells like a new issue.

On a broader note, are you all developing on Macs?

**Ubuntu / Chromium looks better** (same system as above):

![image](https://user-images.githubusercontent.com/5285452/104161678-8c3e8d00-53f3-11eb-8005-175c1828b579.png)
