### ISSUE TITLE
header-styling disappeared in most of daily notes after update

### ISSUE THREAD

**Issue by MaskyS** [Roam-Research/issues#650]
**Describe the bug**
In my daily notes, I copy over a template with various headers. Since the update where the font-weight for the headers were reduced, I've lost all styling on the headers (i.e. they're back to normal-sized text) on every copy of the template + the template itself. _Some_ headers (that weren't copied from the template) remain unaltered, however.

**System Information:**
 - Roam version: 0.7.7-91b28715
 - Device: Laptop
 - OS: Windows
 - Browser: Firefox (App)

**Comment by elizhenning** [comment]
Out of curiosity, is this a LaTeX issue or a CSS issue? I'm having similar sounding problems with LaTeX [https://github.com/Roam-Research/issues/issues/645](https://github.com/Roam-Research/issues/issues/645)

**Comment by MaskyS** [comment]
@elizhenning I'm not using any LaTeX.

**Comment by alessandrosp** [comment]
+1. Same issue. After the most recent update, headers are not styled correctly anymore. I suspect this is due to a change in CSS that conflicts with user-specified CSS rules. In my case, it seems that:

```
.rm-level1, .rm-heading-level-1 > .rm-block__self .rm-block__input {
    font-family: 'Inter', sans-serif;
    font-weight: 400;
    font-size: 1.8em;
}
```

Is overridden by rules such as:

```
textarea {
    font-family: 'Quicksand', sans-serif !important;
    font-size: 1.2em !important;
}
```

While this is an issue (for me and potentially other people), it may not be a bug. One way to fix the issue is to provide custom rules for headers, for example:

```
.rm-heading-level-1 > .rm-block__self .rm-block__input {
    font-weight: 900 !important;
    font-size: 2.4em !important;
}

.rm-heading-level-2 > .rm-block__self .rm-block__input {
    font-weight: 900 !important;
    font-size: 2.0em !important;
}

.rm-heading-level-3 > .rm-block__self .rm-block__input {
    font-weight: 900 !important;
    font-size: 1.6em !important;
}
```

**Comment by Bardia95** [comment]
Not a bug, we changed our CSS
