### ISSUE TITLE
 [[roam/templates]] incorrectly ordering

### ISSUE THREAD

**Issue by axelrau** [Roam-Research/issues#659]
1) I definied a roam template
![image](https://user-images.githubusercontent.com/14819126/103408637-a199f880-4b63-11eb-94a4-903b57b86232.png)
2) Then I used this template on a page
![image](https://user-images.githubusercontent.com/14819126/103408674-c8582f00-4b63-11eb-8115-81b113a48bc5.png)
3.) The subelements are incorrectly ordered

**System Information:**
 - Roam version: 0.7.8-6a388a5e
 - Device: desktop computer
 - OS: Ubuntu 16.04
 - Browser: Chrome

**Comment by Bardia95** [comment]
Fixed
