### ISSUE TITLE
If there is a parentheses in the url, linking doesn't work

### ISSUE THREAD

**Issue by jvdheyden** [Roam-Research/issues#671]
**Describe the bug**

**A clear and concise description of what the bug is.** 

If there is a parentheses in the url, linking doesn't work

**If applicable, add screenshots to help explain your problem. You can paste them in here and they will be uploaded automatically.**

This `[Up](https://en.wikipedia.org/wiki/Up_(film_series))` will not be displayed as link.

**If you have a video of you experiencing the bug, that is also super helpful!**

**To Reproduce**

Try linking an url that contains a closing parenthesis

**System Information:**
 - Roam version: [e.g 0.5.0-43911ff0, find it at the end of the help button pop up]
 - Device: [e.g. iPhone6, desktop computer]
 - OS: [e.g. iOS8.1, Windows, ]
 - Browser [e.g. Chrome, Safari, FireFox, Brave]

**Additional context**

**Comment by theSherwood** [comment]
@jvdheyden Should be working now

**Comment by jvdheyden** [comment]
It was working for a few days, but now its not working anymore
