### ISSUE TITLE
TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by dcervenkov** [Roam-Research/issues#673]
**Describe the bug**

Today, when I opened Roam, at the top of the page there is the following

```
#object[TypeError TypeError: Cannot read property 'insertBefore' of null]
```

Reloading the page, opening in a different browser, etc. didn't help.

![Screenshot from 2021-01-11 10 50 39](https://user-images.githubusercontent.com/23052054/104171670-48ec1a80-5403-11eb-84ea-dd1ff49f6544.png)

**To Reproduce**

1. Login to Roam
4. See bug

**System Information:**
 - Roam version: 0.7.8-54b49a71
 - Device: desktop computer
 - OS: Linux
 - Browser: Chrome, Firefox

**Comment by dcervenkov** [comment]
The problem was caused by a script; please disregard.

**Comment by vanb** [comment]
I have this issue too. What was the user script? I'm not aware of anything I'm running.

**Comment by dcervenkov** [comment]
@vanb For me, it was caused by an outdated version of `random-page-plugin.js` from https://github.com/oschmid/roam-plugins in my `[[roam/js]]`.

**Comment by vanb** [comment]
> @vanb For me, it was caused by an outdated version of `random-page-plugin.js` from https://github.com/oschmid/roam-plugins in my `[[roam/js]]`.

That fixed it! I was looking at Chrome plugins instead of `[[roam/js]]`. Thank you!
