### ISSUE TITLE
YouTube embed doesn't work

### ISSUE THREAD

**Issue by annieeby** [Roam-Research/issues#675]
**Describe the bug**

You seem to have added a new video feature. It doesn't work.

**To Reproduce**

Insert a YouTube link
see grey and white play icon appear
click icon
see embedded video appear
click to play video
see error appear

**System Information:**
 - Roam version: 0.7.8-345999d7
 - Device: computer
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

![image](https://user-images.githubusercontent.com/13418713/104472750-81ae0000-5579-11eb-8894-e06291ccec92.png)

![image](https://user-images.githubusercontent.com/13418713/104472711-765ad480-5579-11eb-9e8f-d13c99c0647c.png)

**Comment by Bardia95** [comment]
Can you send me the exact YouTube link you are trying to view so I can check it against our regex, I've yet to run into this problem, and the youtu.be/8Or link does not seem to be a valid link.

**Comment by annieeby** [comment]
You're right. It's working. I thought I checked it with other videos, but maybe didn't; anyway, everything's working now. Check out this idea though: https://github.com/Roam-Research/issues/issues/649 :)
