### ISSUE TITLE
Drag and drop md and json files to import

### ISSUE THREAD

**Issue by lukesmurray** [Roam-Research/issues#680]
**Describe the problem**

Selecting the import file UI every time you want to import files gets repetitive and frustrating.

I don't mind the dialog once a file is selected.

I propose allowing dragging and dropping files onto roam to import them. 

**Feature implementation**

When you drop the files onto roam the result of selecting those files shows up.

![image](https://user-images.githubusercontent.com/34020210/104952693-f5de0e80-5992-11eb-824b-e203f916cfe2.png)

The user can then choose not to select duplicates... etc.

**Additional context**

Add any other context about the feature here.

**Comment by theSherwood** [comment]
@lukesmurray 
You can now do this. Drag and drop file(s) onto the roam topbar or onto the import modal. The limit of 10 files per import still applies. And the file types are still restricted to markdown and json.

Enjoy!
