### ISSUE TITLE
Safari: page stops to be editable until Roam refresh 

### ISSUE THREAD

**Issue by tombarys** [Roam-Research/issues#682]
**Describe the bug**

_**Safari only bug.**_

**The content of pages stop to be editable and partially clickable after several minutes of use.** 
It is not possible to click-through page, URL or tag links in the page to a new destination.
(Still, clicking references opens the reference context menu and jumping to block is possible.)
It is possible to scroll the content using mouse but clicking does not trigger edit mode.
Jumping to another page (via Find or Create Page – Cmd-U) works well but other pages are usually not editable too.
Left sidebar menu can be opened and is clickable.
Right sidebar menu can be opened too but the content is not editable / clickable.

Video description: https://cln.sh/O9zxCrsJd7zzsI0DPG5Z

**Workaround:**
- Refreshing the page (Cmd-R) works but is not fast enough and user loses focus.

**To Reproduce**

1. Work several minutes with Roam in Safari.
2. See bug

**System Information:**
 - Roam version:  0.7.8-de4308f5
 - Device: iMac / MacBook
 - OS: MacOS Big Sur
 - Browser: Safari 14.0.2

**Additional context**

**Comment by theSherwood** [comment]
@tombarys 
Could you update to the latest version of Roam and let me know if this is still a problem?

I couldn't exactly reproduce this bug. "Work several minutes with Roam in Safari" is something of a wish and a prayer in terms of reproducing a bug.

But I did find that what you described would sometimes happen if something had been dragged across the viewport (a file, some text, sometimes blocks). I pushed a fix for that bug. So if you're still seeing the same problem on Safari, that would be good to know.

**Comment by tombarys** [comment]
@theSherwood Thank you. I am aware that "Work several minutes with Roam in Safari" is a terror but I have had no clue what it was caused by. 

Good news: your fix probably worked. The bug has not occurred in the last two days! I will let you know later. 
Thank you!

**Comment by theSherwood** [comment]
@tombarys Great! I'll close this issue for now, then
