### ISSUE TITLE
Safari: Slected text brackets match error

### ISSUE THREAD

**Issue by Mannixhu** [Roam-Research/issues#685]
**Describe the bug**
Slected text brackets match error in Safari 

https://user-images.githubusercontent.com/16033328/105983244-668fd400-60d3-11eb-990e-90051797809f.mov

**To Reproduce**
1. slect text
2. input [

**System Information:**
 - Roam version: 0.7.8-1a372ead
 - Device: Macbook pro
 - OS: macos Bigsur11.1
 - Browser: Safari14.0.2

**Additional context**
occurred recently, it’s ok last year

**Comment by theSherwood** [comment]
@Mannixhu 
I think this is related to a fix that was pushed recently. I'm unable to reproduce the bug myself but I think I know what's happening.

Few questions:

1. How reliable is this bug?
  - does it happen every time you select text and hit `[`?
2. Could you upload a video of this process happening more slowly?
  - as far as I can tell, you are hitting `[` twice, rapidly
    - is that the case?
    - if it is, upload a video in which you hit `[` once, pause, then hit it again

As I said I can't reproduce the bug myself.

**Comment by Mannixhu** [comment]
> @Mannixhu
> I think this is related to a fix that was pushed recently. I'm unable to reproduce the bug myself but I think I know what's happening.
> 
> Few questions:
> 
> 1. How reliable is this bug?
> 
> * does it happen every time you select text and hit `[`?
> 
> 1. Could you upload a video of this process happening more slowly?
> 
> * as far as I can tell, you are hitting `[` twice, rapidly
>   
>   * is that the case?
>   * if it is, upload a video in which you hit `[` once, pause, then hit it again
> 
> As I said I can't reproduce the bug myself.

1. How reliable is this bug?
* every time
2. Could you upload a video of this process happening more slowly?
  

https://user-images.githubusercontent.com/16033328/106227037-74ed0580-6223-11eb-9200-b613262c5934.mov


   use keycastr to record input

**Comment by Mannixhu** [comment]
thanks, it's fixed now
