### ISSUE TITLE
External markdown links with url schemes other than http(s) no longer work

### ISSUE THREAD

**Issue by acacar** [Roam-Research/issues#690]
**Describe the bug**

It used to be that markdown links to external URLs were clickable and worked whether they were http(s) URLs or some other URL scheme (like message:... or x-url-something). Now only http/https links are clickable, even though all links show the tooltip. I'm not exactly sure when this happened but I noticed it today, and I am sure it was still working correctly on Monday (Jan 25). 

**To Reproduce**

Here is a video showing the bug/regression in action:

![Bug video](https://user-images.githubusercontent.com/1941920/106184802-16883e80-61b3-11eb-81b4-886895f2c81b.mp4)

**System Information:**
 - Roam version: 0.7.8-b9fa4b70
 - Device: Mac
 - OS: macos 11.1
 - Browser: Chrome 88.0.4324.96 (but the same happens in Safari as well)

**Comment by jlmaccal** [comment]
I am also running into this issue. Links that I inserted using the hook app can no longer open when clicked in roam.

**Comment by theSherwood** [comment]
Hey folks, update your roam and this should be fixed

**Comment by acacar** [comment]
Thank you!

**Comment by orkhan10** [comment]
The same problem had been bugging me for the last days, Odtülü  @acacar. ))
Thanks guys.
