### ISSUE TITLE
New page isn't created after putting a word in double brackets

### ISSUE THREAD

**Issue by Anhicek** [Roam-Research/issues#691]
**Describe the bug**

When creating a new page by putting its title in double bracket, nothing happens, the created link is not clickable and no new page can be found in search. 

New page has to be created manually and the previous attempt of creating page with that same title is found in unlinked preferences. 

**To Reproduce**

1. Putting a word in double bracket
2. Click it
3. See bug

**System Information:**
 - Roam version: 0.7.9-4cbc9e34
 - Device: Macbook, iPad, iPhone
 - OS: iOS, MacOS Big sur
 - Browser Safari, Chrome

**Comment by alialili** [comment]
the exact same problem for 0.7.9.
It's okay with 0.7.8

**Comment by stevelw** [comment]
When I had this issue I found hitting ENTER after typing the page name worked.

Working on my current install though.

**Comment by Bardia95** [comment]
fixed
