### ISSUE TITLE
Renaming a page in the sidebar can insidiously force a new page creation

### ISSUE THREAD

**Issue by michaelmangion** [Roam-Research/issues#699]
**Describe the bug**
Renaming a page in the sidebar while having a paragraph containing a link to that page in the main page active forces the creation of another page with the original name rather than updating the page link in the main page.

**To Reproduce**
1. Create a page 'assumption'
2. On **test-page** type: 'Link to [[assumption]] page'
3. With the cursor still on the line above, open the **assumption** page in the sidebar (Ctrl-Shift-O or from search bar)
4. In the sidebar change the page name to **assumptions**
5. The page name changes and updates all linked references - except the reference on **test-page** which remains [[assumption]] and creates a new page **assumption**

**System Information:**
 - Roam version: 0.8.1-80d9e52c
 - Device: MBP 16"
 - OS: MacOS 10.15.5
 - Browser: Chrome

**Additional context**
This may actually be intended behaviour, but I would guess that many people decide to change the name of a page while creating a new link to it and doing it in the sidebar while still working on that line would be the obvious thing to do. This newly created page (and the resulting 'broken' link to the original page) is quite unexpected in this case and could break important links between pages - hence the adjective insidious. Once a link in text that's being edited has been created (which it clearly has because Ctrl-Shift-O opens that page in the sidebar), it should be treated as sacrosanct, even if the user's cursor is on that very link in the main page when the page name it links to is edited in the sidebar. Freezing the text and thereby breaking the page link by creating an entirely new page is completely unexpected and surely can't be what people would intend when doing this.

**Comment by Bardia95** [comment]
Fixed!
