### ISSUE TITLE
Make Quick Capture optional on mobile

### ISSUE THREAD

**Issue by kerim** [Roam-Research/issues#77]
**Describe the problem**

I like to use Roam on mobile to lookup and read information in my database, not just to add new information, however, to do so I must always first dismiss the Quick Capture screen. I would like to be able to bypass or even permanently disable Quick Capture so that I can go straight to whatever page I have bookmarked on mobile rather than having to first dismiss this screen.

**Feature implementation**

I would not seen Quick Capture unless I deliberately chose to invoke it somehow.

**Comment by Stvad** [comment]
Yeah, it should be under its own separate URL. That way it's optional and you can use it from desktop if you want to as-well

**Comment by filipesilva** [comment]
Heya, we've made it not optional, but opt-out. You should be able to tick the checkbox to prefer the full site and that preference will be persistend.

**Comment by pmbauer** [comment]
is there a way to opt back into quick capture without clearing cache?

**Comment by filipesilva** [comment]
@pmbauer yes via the sidebar menu. When you press the graph name there's an option to go back to quick capture. At that point you can see the toggle again.

**Comment by pmbauer** [comment]
@filipesilva 🙇 thanks so much!

**Comment by kerim** [comment]
I'm not seeing the toggle. There is a toggle about whether or not to "nest under quick capture." But not one to hide the quick capture screen altogether. I'm using iOS. I tried removing it from the home screen and re-adding it, but it is still missing.

**Comment by filipesilva** [comment]
@kerim can you show a screenshot of it quick capture looks to you please?

**Comment by kerim** [comment]
![IMG_4156](https://user-images.githubusercontent.com/59976/88643777-ba097100-d0f4-11ea-84ac-081d56693746.jpg)

**Comment by filipesilva** [comment]
@kerim do you have cookies/site data blocked on your browser? One of the ways the toggle can not show up is by not having that available, because we store your choice locally on the device.

**Comment by kerim** [comment]
I only block third-party cookies. Also, I whitelisted roam under my adblocker, but nothing changed.

**Comment by filipesilva** [comment]
What device are you on btw? I think the toggle to block third party cookies on safari iOS is the same that blocks site data, which includes local storage (the thing we use to persist that setting).

**Comment by kerim** [comment]
Yes, I'm using Safari on iOS, but I'm not willing to turn that setting off globally. Is it possible to do it on a per-site basis? Strange that it would block site data, since other web apps are able to save persistent cookies as long as they come from the same domain...

**Comment by filipesilva** [comment]
We don't show the toggle if we can't persist the user choice to local storage, so if local storage isn't available you wouldn't see it at all.

**Comment by kerim** [comment]
Suddenly this is working for me on mobile Safari?

**Comment by filipesilva** [comment]
@kerim hm, maybe it was a missing update? Odd... you seemed to be up to date at the time. Anyway, I'm glad it's sorted.
