### ISSUE TITLE
When pasting text with a trailing slash (like an url), the autocomplete menu appears

### ISSUE THREAD

**Issue by Lunariz** [Roam-Research/issues#8]
**Describe the bug**

![image](https://user-images.githubusercontent.com/6254272/79874795-b1601b00-83e0-11ea-93ff-f704e354654c.png)

**To Reproduce**

1. Copy text that ends in '/', such as an url
2. Paste the text

**System Information:**
 - Device: Desktop computer
 - OS: Windows
 - Browser: Chrome

**Comment by Stvad** [comment]
So this seems to be fixed, but partially? It does not appear straight away on paste, but if I start typing anything after (including space) it pops up
