### ISSUE TITLE
Cursor randomly jumps one character back while typing in cyrillic letters

### ISSUE THREAD

**Issue by SergeyBulatnov** [Roam-Research/issues#82]
Describe the bug

While typing in cyrillic letters cursor occasionally jumps back a position (or maybe more), which leads to correcting a lot of typos and makes user annoyed.

Made a screencast video reproducing this behaviour. Made several attempts, it never took me more than one minute of typing to reproduce it.

[Screencast](https://youtu.be/m5S0bE2vcEM)

To Reproduce

1. Type in any text in cyrillic for a minute
2. See bug

**System Information:**
 - Device: laptop
 - OS: Windows 10
 - Browser Chrome

**Comment by filipesilva** [comment]
@wilkerlucio I think you pushed some changes around this, should it be fixed now?

**Comment by SergeyBulatnov** [comment]
Haven't seen this behaviour for more then a week. Looks like it's fixed.
