### ISSUE TITLE
Attribute modification makes Roam slow

### ISSUE THREAD

**Issue by MatthieuBizien** [Roam-Research/issues#89]
**Describe the bug**

Auto-complete for the ``[[]]`` syntax works wonderfully, and is very fast. It is not the case when I'm editing an attributes:
- Waiting for the auto-complete take 1-3s
- Adding a new letter also needs up to 3s
- Choosing the auto-complete in the list also take 1-3s

**To Reproduce**

1. Go to a random page
2. Create an attribute: ``myattr::``
3. Modify the attribute
4. It's slow :)

**System Information:**
 - Device: Desktop computer
 - OS:  Mac Os
 - Browser: Chrome

**Comment by Stvad** [comment]
Another way to reproduce is to just type `::` in empty block which would invoke the attribute autocomplete (which is slow)

**Comment by panterarocks49** [comment]
Heya, we sped up the attribute search a few weeks back, is this still a problem for you?

**Comment by Stvad** [comment]
thanks, it's a lot better now!

**Comment by MatthieuBizien** [comment]
It's great now, thanks!
