### ISSUE TITLE
Bullet collapsing shortly after opening

### ISSUE THREAD

**Issue by MarcusAGray** [Roam-Research/issues#94]
This bug happens after I open a bullet point to view the sub bullet points. It happens on some bullet points but not others.

Short video;
[Automatic_Collapsing_Bug.zip](https://github.com/Roam-Research/issues/files/4580841/Automatic_Collapsing_Bug.zip)

**To Reproduce**

1. Go to a page with bullet points
2. Click on the button to expand
3. Wait a few secons
4. Bullet point automatically collapses

**System Information:**
 - Device: [HP Pavilion 15-au151sa]
 - OS: [Windowns 10 ]
 - Browser [Chrome]

**Additional context**

**Comment by filipesilva** [comment]
I *think* this is the same as https://github.com/Roam-Research/issues/issues/49. Can you try after force refreshing as mentioned in https://github.com/Roam-Research/issues/issues/49#issuecomment-624005491?

**Comment by MarcusAGray** [comment]
I'm not sure it exactly the same because unlike others in the comments I wasn't losing any content. I went onto Roam again and found that the problem was no longer happening. I force refreshed anyway but the problem does seem to have stopped.

**Comment by MarcusAGray** [comment]
Sorry mate I was too quick to respond. The problem is still there. I tried force refreshing again but that has not fixed it. It seems to be a bit random. Sometimes the bullets collapse, sometimes they don't. If I expand several bullet points on a page eventually some of them will start collapsing on their own.

**Comment by filipesilva** [comment]
Just pushed some new fixes today that I think should impact this. Can you let me know if you're still seeing this after force refreshing?

**Comment by MarcusAGray** [comment]
It doesn't seem to be happening anymore. As far as I can tell the problem is fixed.

**Comment by filipesilva** [comment]
Ok glad to hear. If it comes up again please let me know.
