### ISSUE TITLE
Roam takes >15s to load on mobile

### ISSUE THREAD

**Issue by alexander-kazakov** [Roam-Research/issues#95]
Roam typically opens quite slowly, but on mobile (OnePlus 5, Google Chrome) it takes 10-20 seconds to load.

Which is way too long when you want to write down an unexpected new idea.

**To Reproduce**
- Log in to roamresearch previously
- Open roamresearch.com in browser
- Click Sign In (why doesn't it recognize that I'm logged in automatically?)
Observer the loading screen for 10-20 sec before seeing quick capture screen

![Screenshot_20200505-162259](https://user-images.githubusercontent.com/9076886/81077533-602a4e00-8eed-11ea-87b4-38c5a5fe1af2.jpg)
![Screenshot_20200505-162344](https://user-images.githubusercontent.com/9076886/81077536-60c2e480-8eed-11ea-82fd-9bc5caa29505.jpg)

**Comment by dmackerman** [comment]
This isn't isolated on mobile. The app takes 10s+ to load for me on Desktop as well. 

Latest Chrome, 6-Core i7 hardware.

**Comment by filipesilva** [comment]
Are you still seeing these long load times? We've recently added a lot of extra capacity to our servers. If you have a really large database and a somewhat old phone, I wouldn't be too surprised it takes a while. But it shouldn't just sit there forever.

**Comment by alexander-kazakov** [comment]
Hi Filipe! Indeed, now it loads within 1-2 seconds. Super nice!
