### ISSUE TITLE
Show version number of release with the dot

### ISSUE THREAD

**Issue by anshbansal** [Roam-Research/issues#96]
**Describe the problem**

It would be quite simple to know whether I have the latest changes or not if I could see the release version number. Simple text, nothing fancy. Then if a problem happens then I can give the version number alongwith the problem description.

**Feature implementation**

Simple text showing the release number. Maybe near the sync dot.

**Comment by filipesilva** [comment]
Heya, we're going to show this on the help menu. Should be out tomorrow or so.

**Comment by anshbansal** [comment]
You should probably also change the Bug Template System Information to also add Version Number. That should be the easiest way to make everyone aware of this and get useful information in bug reports.

**Comment by filipesilva** [comment]
Yup, just added!
